package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AccountUserPermissionAssoc generated by hbm2java
 */
public class AccountUserPermissionAssoc implements java.io.Serializable {

	private AccountUserPermissionAssocId id;

	private boolean isAllowed;

	public AccountUserPermissionAssoc() {
	}

	public AccountUserPermissionAssoc(AccountUserPermissionAssocId id, boolean isAllowed) {
		this.id = id;
		this.isAllowed = isAllowed;
	}

	public AccountUserPermissionAssocId getId() {
		return this.id;
	}

	public void setId(AccountUserPermissionAssocId id) {
		this.id = id;
	}

	public boolean isIsAllowed() {
		return this.isAllowed;
	}

	public void setIsAllowed(boolean isAllowed) {
		this.isAllowed = isAllowed;
	}

}
