package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AccountUserPermissionAssocId generated by hbm2java
 */
public class AccountUserPermissionAssocId implements java.io.Serializable {

	private int accountId;

	private int userId;

	private int permissionId;

	public AccountUserPermissionAssocId() {
	}

	public AccountUserPermissionAssocId(int accountId, int userId, int permissionId) {
		this.accountId = accountId;
		this.userId = userId;
		this.permissionId = permissionId;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountUserPermissionAssocId))
			return false;
		AccountUserPermissionAssocId castOther = (AccountUserPermissionAssocId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getUserId() == castOther.getUserId()) && (this.getPermissionId() == castOther.getPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getPermissionId();
		return result;
	}

}
