package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AccountPreferenceAssocId generated by hbm2java
 */
public class AccountPreferenceAssocId implements java.io.Serializable {

	private int accountId;

	private int preferenceId;

	public AccountPreferenceAssocId() {
	}

	public AccountPreferenceAssocId(int accountId, int preferenceId) {
		this.accountId = accountId;
		this.preferenceId = preferenceId;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public int getPreferenceId() {
		return this.preferenceId;
	}

	public void setPreferenceId(int preferenceId) {
		this.preferenceId = preferenceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountPreferenceAssocId))
			return false;
		AccountPreferenceAssocId castOther = (AccountPreferenceAssocId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getPreferenceId() == castOther.getPreferenceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getPreferenceId();
		return result;
	}

}
