package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AccountUserAssocId generated by hbm2java
 */
public class AccountUserAssocId implements java.io.Serializable {

	private int accountId;

	private int userId;

	public AccountUserAssocId() {
	}

	public AccountUserAssocId(int accountId, int userId) {
		this.accountId = accountId;
		this.userId = userId;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountUserAssocId))
			return false;
		AccountUserAssocId castOther = (AccountUserAssocId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
