package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AccountPreferenceAssoc generated by hbm2java
 */
public class AccountPreferenceAssoc implements java.io.Serializable {

	private AccountPreferenceAssocId id;

	private String value;

	public AccountPreferenceAssoc() {
	}

	public AccountPreferenceAssoc(AccountPreferenceAssocId id, String value) {
		this.id = id;
		this.value = value;
	}

	public AccountPreferenceAssocId getId() {
		return this.id;
	}

	public void setId(AccountPreferenceAssocId id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
