package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AclsChannel generated by hbm2java
 */
public class AclsChannel implements java.io.Serializable {

	private AclsChannelId id;

	public AclsChannel() {
	}

	public AclsChannel(AclsChannelId id) {
		this.id = id;
	}

	public AclsChannelId getId() {
		return this.id;
	}

	public void setId(AclsChannelId id) {
		this.id = id;
	}

}
