package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * Acls generated by hbm2java
 */
public class Acls implements java.io.Serializable {

	private AclsId id;

	public Acls() {
	}

	public Acls(AclsId id) {
		this.id = id;
	}

	public AclsId getId() {
		return this.id;
	}

	public void setId(AclsId id) {
		this.id = id;
	}

}
