package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AdCategoryAssoc generated by hbm2java
 */
public class AdCategoryAssoc implements java.io.Serializable {

	private Integer adCategoryAssocId;

	private int categoryId;

	private int adId;

	public AdCategoryAssoc() {
	}

	public AdCategoryAssoc(int categoryId, int adId) {
		this.categoryId = categoryId;
		this.adId = adId;
	}

	public Integer getAdCategoryAssocId() {
		return this.adCategoryAssocId;
	}

	public void setAdCategoryAssocId(Integer adCategoryAssocId) {
		this.adCategoryAssocId = adCategoryAssocId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

}
