package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * AdZoneAssoc generated by hbm2java
 */
public class AdZoneAssoc implements java.io.Serializable {

	private Integer adZoneAssocId;

	private Integer zoneId;

	private Integer adId;

	private Double priority;

	private short linkType;

	private Double priorityFactor;

	private boolean toBeDelivered;

	public AdZoneAssoc() {
	}

	public AdZoneAssoc(short linkType, boolean toBeDelivered) {
		this.linkType = linkType;
		this.toBeDelivered = toBeDelivered;
	}

	public AdZoneAssoc(Integer zoneId, Integer adId, Double priority, short linkType, Double priorityFactor, boolean toBeDelivered) {
		this.zoneId = zoneId;
		this.adId = adId;
		this.priority = priority;
		this.linkType = linkType;
		this.priorityFactor = priorityFactor;
		this.toBeDelivered = toBeDelivered;
	}

	public Integer getAdZoneAssocId() {
		return this.adZoneAssocId;
	}

	public void setAdZoneAssocId(Integer adZoneAssocId) {
		this.adZoneAssocId = adZoneAssocId;
	}

	public Integer getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(Integer zoneId) {
		this.zoneId = zoneId;
	}

	public Integer getAdId() {
		return this.adId;
	}

	public void setAdId(Integer adId) {
		this.adId = adId;
	}

	public Double getPriority() {
		return this.priority;
	}

	public void setPriority(Double priority) {
		this.priority = priority;
	}

	public short getLinkType() {
		return this.linkType;
	}

	public void setLinkType(short linkType) {
		this.linkType = linkType;
	}

	public Double getPriorityFactor() {
		return this.priorityFactor;
	}

	public void setPriorityFactor(Double priorityFactor) {
		this.priorityFactor = priorityFactor;
	}

	public boolean isToBeDelivered() {
		return this.toBeDelivered;
	}

	public void setToBeDelivered(boolean toBeDelivered) {
		this.toBeDelivered = toBeDelivered;
	}

}
