package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Affiliates generated by hbm2java
 */
public class Affiliates implements java.io.Serializable {

	private Integer affiliateid;

	private int agencyid;

	private String name;

	private String mnemonic;

	private String comments;

	private String contact;

	private String email;

	private String website;

	private Date updated;

	private Integer anWebsiteId;

	private String oacCountryCode;

	private Integer oacLanguageId;

	private Integer oacCategoryId;

	private Integer asWebsiteId;

	private Integer accountId;

	public Affiliates() {
	}

	public Affiliates(int agencyid, String name, String mnemonic, String email, Date updated, String oacCountryCode) {
		this.agencyid = agencyid;
		this.name = name;
		this.mnemonic = mnemonic;
		this.email = email;
		this.updated = updated;
		this.oacCountryCode = oacCountryCode;
	}

	public Affiliates(int agencyid, String name, String mnemonic, String comments, String contact, String email, String website, Date updated, Integer anWebsiteId, String oacCountryCode,
			Integer oacLanguageId, Integer oacCategoryId, Integer asWebsiteId, Integer accountId) {
		this.agencyid = agencyid;
		this.name = name;
		this.mnemonic = mnemonic;
		this.comments = comments;
		this.contact = contact;
		this.email = email;
		this.website = website;
		this.updated = updated;
		this.anWebsiteId = anWebsiteId;
		this.oacCountryCode = oacCountryCode;
		this.oacLanguageId = oacLanguageId;
		this.oacCategoryId = oacCategoryId;
		this.asWebsiteId = asWebsiteId;
		this.accountId = accountId;
	}

	public Integer getAffiliateid() {
		return this.affiliateid;
	}

	public void setAffiliateid(Integer affiliateid) {
		this.affiliateid = affiliateid;
	}

	public int getAgencyid() {
		return this.agencyid;
	}

	public void setAgencyid(int agencyid) {
		this.agencyid = agencyid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMnemonic() {
		return this.mnemonic;
	}

	public void setMnemonic(String mnemonic) {
		this.mnemonic = mnemonic;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Integer getAnWebsiteId() {
		return this.anWebsiteId;
	}

	public void setAnWebsiteId(Integer anWebsiteId) {
		this.anWebsiteId = anWebsiteId;
	}

	public String getOacCountryCode() {
		return this.oacCountryCode;
	}

	public void setOacCountryCode(String oacCountryCode) {
		this.oacCountryCode = oacCountryCode;
	}

	public Integer getOacLanguageId() {
		return this.oacLanguageId;
	}

	public void setOacLanguageId(Integer oacLanguageId) {
		this.oacLanguageId = oacLanguageId;
	}

	public Integer getOacCategoryId() {
		return this.oacCategoryId;
	}

	public void setOacCategoryId(Integer oacCategoryId) {
		this.oacCategoryId = oacCategoryId;
	}

	public Integer getAsWebsiteId() {
		return this.asWebsiteId;
	}

	public void setAsWebsiteId(Integer asWebsiteId) {
		this.asWebsiteId = asWebsiteId;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

}
