package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ApplicationVariable generated by hbm2java
 */
public class ApplicationVariable implements java.io.Serializable {

	private String name;

	private String value;

	public ApplicationVariable() {
	}

	public ApplicationVariable(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
