package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * BannerVastElementId generated by hbm2java
 */
public class BannerVastElementId implements java.io.Serializable {

	private int bannerVastElementId;

	private int bannerId;

	private String vastElementType;

	private String vastVideoId;

	private Integer vastVideoDuration;

	private String vastVideoDelivery;

	private String vastVideoType;

	private String vastVideoBitrate;

	private Integer vastVideoHeight;

	private Integer vastVideoWidth;

	private String vastVideoOutgoingFilename;

	private Integer vastCompanionBannerId;

	private Integer vastOverlayHeight;

	private Integer vastOverlayWidth;

	private String vastVideoClickthroughUrl;

	private String vastOverlayAction;

	private String vastOverlayFormat;

	private String vastOverlayTextTitle;

	private String vastOverlayTextDescription;

	private String vastOverlayTextCall;

	private String vastCreativeType;

	private String vastThirdpartyImpression;

	public BannerVastElementId() {
	}

	public BannerVastElementId(int bannerVastElementId, int bannerId, String vastElementType) {
		this.bannerVastElementId = bannerVastElementId;
		this.bannerId = bannerId;
		this.vastElementType = vastElementType;
	}

	public BannerVastElementId(int bannerVastElementId, int bannerId, String vastElementType, String vastVideoId, Integer vastVideoDuration, String vastVideoDelivery, String vastVideoType,
			String vastVideoBitrate, Integer vastVideoHeight, Integer vastVideoWidth, String vastVideoOutgoingFilename, Integer vastCompanionBannerId, Integer vastOverlayHeight,
			Integer vastOverlayWidth, String vastVideoClickthroughUrl, String vastOverlayAction, String vastOverlayFormat, String vastOverlayTextTitle, String vastOverlayTextDescription,
			String vastOverlayTextCall, String vastCreativeType, String vastThirdpartyImpression) {
		this.bannerVastElementId = bannerVastElementId;
		this.bannerId = bannerId;
		this.vastElementType = vastElementType;
		this.vastVideoId = vastVideoId;
		this.vastVideoDuration = vastVideoDuration;
		this.vastVideoDelivery = vastVideoDelivery;
		this.vastVideoType = vastVideoType;
		this.vastVideoBitrate = vastVideoBitrate;
		this.vastVideoHeight = vastVideoHeight;
		this.vastVideoWidth = vastVideoWidth;
		this.vastVideoOutgoingFilename = vastVideoOutgoingFilename;
		this.vastCompanionBannerId = vastCompanionBannerId;
		this.vastOverlayHeight = vastOverlayHeight;
		this.vastOverlayWidth = vastOverlayWidth;
		this.vastVideoClickthroughUrl = vastVideoClickthroughUrl;
		this.vastOverlayAction = vastOverlayAction;
		this.vastOverlayFormat = vastOverlayFormat;
		this.vastOverlayTextTitle = vastOverlayTextTitle;
		this.vastOverlayTextDescription = vastOverlayTextDescription;
		this.vastOverlayTextCall = vastOverlayTextCall;
		this.vastCreativeType = vastCreativeType;
		this.vastThirdpartyImpression = vastThirdpartyImpression;
	}

	public int getBannerVastElementId() {
		return this.bannerVastElementId;
	}

	public void setBannerVastElementId(int bannerVastElementId) {
		this.bannerVastElementId = bannerVastElementId;
	}

	public int getBannerId() {
		return this.bannerId;
	}

	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}

	public String getVastElementType() {
		return this.vastElementType;
	}

	public void setVastElementType(String vastElementType) {
		this.vastElementType = vastElementType;
	}

	public String getVastVideoId() {
		return this.vastVideoId;
	}

	public void setVastVideoId(String vastVideoId) {
		this.vastVideoId = vastVideoId;
	}

	public Integer getVastVideoDuration() {
		return this.vastVideoDuration;
	}

	public void setVastVideoDuration(Integer vastVideoDuration) {
		this.vastVideoDuration = vastVideoDuration;
	}

	public String getVastVideoDelivery() {
		return this.vastVideoDelivery;
	}

	public void setVastVideoDelivery(String vastVideoDelivery) {
		this.vastVideoDelivery = vastVideoDelivery;
	}

	public String getVastVideoType() {
		return this.vastVideoType;
	}

	public void setVastVideoType(String vastVideoType) {
		this.vastVideoType = vastVideoType;
	}

	public String getVastVideoBitrate() {
		return this.vastVideoBitrate;
	}

	public void setVastVideoBitrate(String vastVideoBitrate) {
		this.vastVideoBitrate = vastVideoBitrate;
	}

	public Integer getVastVideoHeight() {
		return this.vastVideoHeight;
	}

	public void setVastVideoHeight(Integer vastVideoHeight) {
		this.vastVideoHeight = vastVideoHeight;
	}

	public Integer getVastVideoWidth() {
		return this.vastVideoWidth;
	}

	public void setVastVideoWidth(Integer vastVideoWidth) {
		this.vastVideoWidth = vastVideoWidth;
	}

	public String getVastVideoOutgoingFilename() {
		return this.vastVideoOutgoingFilename;
	}

	public void setVastVideoOutgoingFilename(String vastVideoOutgoingFilename) {
		this.vastVideoOutgoingFilename = vastVideoOutgoingFilename;
	}

	public Integer getVastCompanionBannerId() {
		return this.vastCompanionBannerId;
	}

	public void setVastCompanionBannerId(Integer vastCompanionBannerId) {
		this.vastCompanionBannerId = vastCompanionBannerId;
	}

	public Integer getVastOverlayHeight() {
		return this.vastOverlayHeight;
	}

	public void setVastOverlayHeight(Integer vastOverlayHeight) {
		this.vastOverlayHeight = vastOverlayHeight;
	}

	public Integer getVastOverlayWidth() {
		return this.vastOverlayWidth;
	}

	public void setVastOverlayWidth(Integer vastOverlayWidth) {
		this.vastOverlayWidth = vastOverlayWidth;
	}

	public String getVastVideoClickthroughUrl() {
		return this.vastVideoClickthroughUrl;
	}

	public void setVastVideoClickthroughUrl(String vastVideoClickthroughUrl) {
		this.vastVideoClickthroughUrl = vastVideoClickthroughUrl;
	}

	public String getVastOverlayAction() {
		return this.vastOverlayAction;
	}

	public void setVastOverlayAction(String vastOverlayAction) {
		this.vastOverlayAction = vastOverlayAction;
	}

	public String getVastOverlayFormat() {
		return this.vastOverlayFormat;
	}

	public void setVastOverlayFormat(String vastOverlayFormat) {
		this.vastOverlayFormat = vastOverlayFormat;
	}

	public String getVastOverlayTextTitle() {
		return this.vastOverlayTextTitle;
	}

	public void setVastOverlayTextTitle(String vastOverlayTextTitle) {
		this.vastOverlayTextTitle = vastOverlayTextTitle;
	}

	public String getVastOverlayTextDescription() {
		return this.vastOverlayTextDescription;
	}

	public void setVastOverlayTextDescription(String vastOverlayTextDescription) {
		this.vastOverlayTextDescription = vastOverlayTextDescription;
	}

	public String getVastOverlayTextCall() {
		return this.vastOverlayTextCall;
	}

	public void setVastOverlayTextCall(String vastOverlayTextCall) {
		this.vastOverlayTextCall = vastOverlayTextCall;
	}

	public String getVastCreativeType() {
		return this.vastCreativeType;
	}

	public void setVastCreativeType(String vastCreativeType) {
		this.vastCreativeType = vastCreativeType;
	}

	public String getVastThirdpartyImpression() {
		return this.vastThirdpartyImpression;
	}

	public void setVastThirdpartyImpression(String vastThirdpartyImpression) {
		this.vastThirdpartyImpression = vastThirdpartyImpression;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BannerVastElementId))
			return false;
		BannerVastElementId castOther = (BannerVastElementId) other;

		return (this.getBannerVastElementId() == castOther.getBannerVastElementId())
				&& (this.getBannerId() == castOther.getBannerId())
				&& ((this.getVastElementType() == castOther.getVastElementType()) || (this.getVastElementType() != null && castOther.getVastElementType() != null && this.getVastElementType().equals(
						castOther.getVastElementType())))
				&& ((this.getVastVideoId() == castOther.getVastVideoId()) || (this.getVastVideoId() != null && castOther.getVastVideoId() != null && this.getVastVideoId().equals(
						castOther.getVastVideoId())))
				&& ((this.getVastVideoDuration() == castOther.getVastVideoDuration()) || (this.getVastVideoDuration() != null && castOther.getVastVideoDuration() != null && this
						.getVastVideoDuration().equals(castOther.getVastVideoDuration())))
				&& ((this.getVastVideoDelivery() == castOther.getVastVideoDelivery()) || (this.getVastVideoDelivery() != null && castOther.getVastVideoDelivery() != null && this
						.getVastVideoDelivery().equals(castOther.getVastVideoDelivery())))
				&& ((this.getVastVideoType() == castOther.getVastVideoType()) || (this.getVastVideoType() != null && castOther.getVastVideoType() != null && this.getVastVideoType().equals(
						castOther.getVastVideoType())))
				&& ((this.getVastVideoBitrate() == castOther.getVastVideoBitrate()) || (this.getVastVideoBitrate() != null && castOther.getVastVideoBitrate() != null && this.getVastVideoBitrate()
						.equals(castOther.getVastVideoBitrate())))
				&& ((this.getVastVideoHeight() == castOther.getVastVideoHeight()) || (this.getVastVideoHeight() != null && castOther.getVastVideoHeight() != null && this.getVastVideoHeight().equals(
						castOther.getVastVideoHeight())))
				&& ((this.getVastVideoWidth() == castOther.getVastVideoWidth()) || (this.getVastVideoWidth() != null && castOther.getVastVideoWidth() != null && this.getVastVideoWidth().equals(
						castOther.getVastVideoWidth())))
				&& ((this.getVastVideoOutgoingFilename() == castOther.getVastVideoOutgoingFilename()) || (this.getVastVideoOutgoingFilename() != null
						&& castOther.getVastVideoOutgoingFilename() != null && this.getVastVideoOutgoingFilename().equals(castOther.getVastVideoOutgoingFilename())))
				&& ((this.getVastCompanionBannerId() == castOther.getVastCompanionBannerId()) || (this.getVastCompanionBannerId() != null && castOther.getVastCompanionBannerId() != null && this
						.getVastCompanionBannerId().equals(castOther.getVastCompanionBannerId())))
				&& ((this.getVastOverlayHeight() == castOther.getVastOverlayHeight()) || (this.getVastOverlayHeight() != null && castOther.getVastOverlayHeight() != null && this
						.getVastOverlayHeight().equals(castOther.getVastOverlayHeight())))
				&& ((this.getVastOverlayWidth() == castOther.getVastOverlayWidth()) || (this.getVastOverlayWidth() != null && castOther.getVastOverlayWidth() != null && this.getVastOverlayWidth()
						.equals(castOther.getVastOverlayWidth())))
				&& ((this.getVastVideoClickthroughUrl() == castOther.getVastVideoClickthroughUrl()) || (this.getVastVideoClickthroughUrl() != null && castOther.getVastVideoClickthroughUrl() != null && this
						.getVastVideoClickthroughUrl().equals(castOther.getVastVideoClickthroughUrl())))
				&& ((this.getVastOverlayAction() == castOther.getVastOverlayAction()) || (this.getVastOverlayAction() != null && castOther.getVastOverlayAction() != null && this
						.getVastOverlayAction().equals(castOther.getVastOverlayAction())))
				&& ((this.getVastOverlayFormat() == castOther.getVastOverlayFormat()) || (this.getVastOverlayFormat() != null && castOther.getVastOverlayFormat() != null && this
						.getVastOverlayFormat().equals(castOther.getVastOverlayFormat())))
				&& ((this.getVastOverlayTextTitle() == castOther.getVastOverlayTextTitle()) || (this.getVastOverlayTextTitle() != null && castOther.getVastOverlayTextTitle() != null && this
						.getVastOverlayTextTitle().equals(castOther.getVastOverlayTextTitle())))
				&& ((this.getVastOverlayTextDescription() == castOther.getVastOverlayTextDescription()) || (this.getVastOverlayTextDescription() != null
						&& castOther.getVastOverlayTextDescription() != null && this.getVastOverlayTextDescription().equals(castOther.getVastOverlayTextDescription())))
				&& ((this.getVastOverlayTextCall() == castOther.getVastOverlayTextCall()) || (this.getVastOverlayTextCall() != null && castOther.getVastOverlayTextCall() != null && this
						.getVastOverlayTextCall().equals(castOther.getVastOverlayTextCall())))
				&& ((this.getVastCreativeType() == castOther.getVastCreativeType()) || (this.getVastCreativeType() != null && castOther.getVastCreativeType() != null && this.getVastCreativeType()
						.equals(castOther.getVastCreativeType())))
				&& ((this.getVastThirdpartyImpression() == castOther.getVastThirdpartyImpression()) || (this.getVastThirdpartyImpression() != null && castOther.getVastThirdpartyImpression() != null && this
						.getVastThirdpartyImpression().equals(castOther.getVastThirdpartyImpression())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBannerVastElementId();
		result = 37 * result + this.getBannerId();
		result = 37 * result + (getVastElementType() == null ? 0 : this.getVastElementType().hashCode());
		result = 37 * result + (getVastVideoId() == null ? 0 : this.getVastVideoId().hashCode());
		result = 37 * result + (getVastVideoDuration() == null ? 0 : this.getVastVideoDuration().hashCode());
		result = 37 * result + (getVastVideoDelivery() == null ? 0 : this.getVastVideoDelivery().hashCode());
		result = 37 * result + (getVastVideoType() == null ? 0 : this.getVastVideoType().hashCode());
		result = 37 * result + (getVastVideoBitrate() == null ? 0 : this.getVastVideoBitrate().hashCode());
		result = 37 * result + (getVastVideoHeight() == null ? 0 : this.getVastVideoHeight().hashCode());
		result = 37 * result + (getVastVideoWidth() == null ? 0 : this.getVastVideoWidth().hashCode());
		result = 37 * result + (getVastVideoOutgoingFilename() == null ? 0 : this.getVastVideoOutgoingFilename().hashCode());
		result = 37 * result + (getVastCompanionBannerId() == null ? 0 : this.getVastCompanionBannerId().hashCode());
		result = 37 * result + (getVastOverlayHeight() == null ? 0 : this.getVastOverlayHeight().hashCode());
		result = 37 * result + (getVastOverlayWidth() == null ? 0 : this.getVastOverlayWidth().hashCode());
		result = 37 * result + (getVastVideoClickthroughUrl() == null ? 0 : this.getVastVideoClickthroughUrl().hashCode());
		result = 37 * result + (getVastOverlayAction() == null ? 0 : this.getVastOverlayAction().hashCode());
		result = 37 * result + (getVastOverlayFormat() == null ? 0 : this.getVastOverlayFormat().hashCode());
		result = 37 * result + (getVastOverlayTextTitle() == null ? 0 : this.getVastOverlayTextTitle().hashCode());
		result = 37 * result + (getVastOverlayTextDescription() == null ? 0 : this.getVastOverlayTextDescription().hashCode());
		result = 37 * result + (getVastOverlayTextCall() == null ? 0 : this.getVastOverlayTextCall().hashCode());
		result = 37 * result + (getVastCreativeType() == null ? 0 : this.getVastCreativeType().hashCode());
		result = 37 * result + (getVastThirdpartyImpression() == null ? 0 : this.getVastThirdpartyImpression().hashCode());
		return result;
	}

}
