package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Banners generated by hbm2java
 */
public class Banners implements java.io.Serializable {

	private Integer bannerid;

	private int campaignid;

	private String contenttype;

	private int pluginversion;

	private String storagetype;

	private String filename;

	private String imageurl;

	private String htmltemplate;

	private String htmlcache;

	private short width;

	private short height;

	private byte weight;

	private byte seq;

	private String target;

	private String url;

	private String alt;

	private String statustext;

	private String bannertext;

	private String description;

	private String adserver;

	private int block;

	private int capping;

	private int sessionCapping;

	private String compiledlimitation;

	private String aclPlugins;

	private String append;

	private byte bannertype;

	private String altFilename;

	private String altImageurl;

	private String altContenttype;

	private String comments;

	private Date updated;

	private Date aclsUpdated;

	private String keyword;

	private boolean transparent;

	private String parameters;

	private Integer anBannerId;

	private Integer asBannerId;

	private int status;

	private byte adDirectStatus;

	private byte adDirectRejectionReasonId;

	private String extBannertype;

	private String prepend;

	public Banners() {
	}

	public Banners(int campaignid, String contenttype, int pluginversion, String storagetype, String filename, String imageurl, String htmltemplate, String htmlcache, short width, short height,
			byte weight, byte seq, String target, String url, String alt, String statustext, String bannertext, String description, String adserver, int block, int capping, int sessionCapping,
			String compiledlimitation, String append, byte bannertype, String altFilename, String altImageurl, String altContenttype, Date updated, Date aclsUpdated, String keyword,
			boolean transparent, int status, byte adDirectStatus, byte adDirectRejectionReasonId, String prepend) {
		this.campaignid = campaignid;
		this.contenttype = contenttype;
		this.pluginversion = pluginversion;
		this.storagetype = storagetype;
		this.filename = filename;
		this.imageurl = imageurl;
		this.htmltemplate = htmltemplate;
		this.htmlcache = htmlcache;
		this.width = width;
		this.height = height;
		this.weight = weight;
		this.seq = seq;
		this.target = target;
		this.url = url;
		this.alt = alt;
		this.statustext = statustext;
		this.bannertext = bannertext;
		this.description = description;
		this.adserver = adserver;
		this.block = block;
		this.capping = capping;
		this.sessionCapping = sessionCapping;
		this.compiledlimitation = compiledlimitation;
		this.append = append;
		this.bannertype = bannertype;
		this.altFilename = altFilename;
		this.altImageurl = altImageurl;
		this.altContenttype = altContenttype;
		this.updated = updated;
		this.aclsUpdated = aclsUpdated;
		this.keyword = keyword;
		this.transparent = transparent;
		this.status = status;
		this.adDirectStatus = adDirectStatus;
		this.adDirectRejectionReasonId = adDirectRejectionReasonId;
		this.prepend = prepend;
	}

	public Banners(int campaignid, String contenttype, int pluginversion, String storagetype, String filename, String imageurl, String htmltemplate, String htmlcache, short width, short height,
			byte weight, byte seq, String target, String url, String alt, String statustext, String bannertext, String description, String adserver, int block, int capping, int sessionCapping,
			String compiledlimitation, String aclPlugins, String append, byte bannertype, String altFilename, String altImageurl, String altContenttype, String comments, Date updated,
			Date aclsUpdated, String keyword, boolean transparent, String parameters, Integer anBannerId, Integer asBannerId, int status, byte adDirectStatus, byte adDirectRejectionReasonId,
			String extBannertype, String prepend) {
		this.campaignid = campaignid;
		this.contenttype = contenttype;
		this.pluginversion = pluginversion;
		this.storagetype = storagetype;
		this.filename = filename;
		this.imageurl = imageurl;
		this.htmltemplate = htmltemplate;
		this.htmlcache = htmlcache;
		this.width = width;
		this.height = height;
		this.weight = weight;
		this.seq = seq;
		this.target = target;
		this.url = url;
		this.alt = alt;
		this.statustext = statustext;
		this.bannertext = bannertext;
		this.description = description;
		this.adserver = adserver;
		this.block = block;
		this.capping = capping;
		this.sessionCapping = sessionCapping;
		this.compiledlimitation = compiledlimitation;
		this.aclPlugins = aclPlugins;
		this.append = append;
		this.bannertype = bannertype;
		this.altFilename = altFilename;
		this.altImageurl = altImageurl;
		this.altContenttype = altContenttype;
		this.comments = comments;
		this.updated = updated;
		this.aclsUpdated = aclsUpdated;
		this.keyword = keyword;
		this.transparent = transparent;
		this.parameters = parameters;
		this.anBannerId = anBannerId;
		this.asBannerId = asBannerId;
		this.status = status;
		this.adDirectStatus = adDirectStatus;
		this.adDirectRejectionReasonId = adDirectRejectionReasonId;
		this.extBannertype = extBannertype;
		this.prepend = prepend;
	}

	public Integer getBannerid() {
		return this.bannerid;
	}

	public void setBannerid(Integer bannerid) {
		this.bannerid = bannerid;
	}

	public int getCampaignid() {
		return this.campaignid;
	}

	public void setCampaignid(int campaignid) {
		this.campaignid = campaignid;
	}

	public String getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(String contenttype) {
		this.contenttype = contenttype;
	}

	public int getPluginversion() {
		return this.pluginversion;
	}

	public void setPluginversion(int pluginversion) {
		this.pluginversion = pluginversion;
	}

	public String getStoragetype() {
		return this.storagetype;
	}

	public void setStoragetype(String storagetype) {
		this.storagetype = storagetype;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getImageurl() {
		return this.imageurl;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	public String getHtmltemplate() {
		return this.htmltemplate;
	}

	public void setHtmltemplate(String htmltemplate) {
		this.htmltemplate = htmltemplate;
	}

	public String getHtmlcache() {
		return this.htmlcache;
	}

	public void setHtmlcache(String htmlcache) {
		this.htmlcache = htmlcache;
	}

	public short getWidth() {
		return this.width;
	}

	public void setWidth(short width) {
		this.width = width;
	}

	public short getHeight() {
		return this.height;
	}

	public void setHeight(short height) {
		this.height = height;
	}

	public byte getWeight() {
		return this.weight;
	}

	public void setWeight(byte weight) {
		this.weight = weight;
	}

	public byte getSeq() {
		return this.seq;
	}

	public void setSeq(byte seq) {
		this.seq = seq;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getAlt() {
		return this.alt;
	}

	public void setAlt(String alt) {
		this.alt = alt;
	}

	public String getStatustext() {
		return this.statustext;
	}

	public void setStatustext(String statustext) {
		this.statustext = statustext;
	}

	public String getBannertext() {
		return this.bannertext;
	}

	public void setBannertext(String bannertext) {
		this.bannertext = bannertext;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAdserver() {
		return this.adserver;
	}

	public void setAdserver(String adserver) {
		this.adserver = adserver;
	}

	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	public int getCapping() {
		return this.capping;
	}

	public void setCapping(int capping) {
		this.capping = capping;
	}

	public int getSessionCapping() {
		return this.sessionCapping;
	}

	public void setSessionCapping(int sessionCapping) {
		this.sessionCapping = sessionCapping;
	}

	public String getCompiledlimitation() {
		return this.compiledlimitation;
	}

	public void setCompiledlimitation(String compiledlimitation) {
		this.compiledlimitation = compiledlimitation;
	}

	public String getAclPlugins() {
		return this.aclPlugins;
	}

	public void setAclPlugins(String aclPlugins) {
		this.aclPlugins = aclPlugins;
	}

	public String getAppend() {
		return this.append;
	}

	public void setAppend(String append) {
		this.append = append;
	}

	public byte getBannertype() {
		return this.bannertype;
	}

	public void setBannertype(byte bannertype) {
		this.bannertype = bannertype;
	}

	public String getAltFilename() {
		return this.altFilename;
	}

	public void setAltFilename(String altFilename) {
		this.altFilename = altFilename;
	}

	public String getAltImageurl() {
		return this.altImageurl;
	}

	public void setAltImageurl(String altImageurl) {
		this.altImageurl = altImageurl;
	}

	public String getAltContenttype() {
		return this.altContenttype;
	}

	public void setAltContenttype(String altContenttype) {
		this.altContenttype = altContenttype;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Date getAclsUpdated() {
		return this.aclsUpdated;
	}

	public void setAclsUpdated(Date aclsUpdated) {
		this.aclsUpdated = aclsUpdated;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public boolean isTransparent() {
		return this.transparent;
	}

	public void setTransparent(boolean transparent) {
		this.transparent = transparent;
	}

	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	public Integer getAnBannerId() {
		return this.anBannerId;
	}

	public void setAnBannerId(Integer anBannerId) {
		this.anBannerId = anBannerId;
	}

	public Integer getAsBannerId() {
		return this.asBannerId;
	}

	public void setAsBannerId(Integer asBannerId) {
		this.asBannerId = asBannerId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public byte getAdDirectStatus() {
		return this.adDirectStatus;
	}

	public void setAdDirectStatus(byte adDirectStatus) {
		this.adDirectStatus = adDirectStatus;
	}

	public byte getAdDirectRejectionReasonId() {
		return this.adDirectRejectionReasonId;
	}

	public void setAdDirectRejectionReasonId(byte adDirectRejectionReasonId) {
		this.adDirectRejectionReasonId = adDirectRejectionReasonId;
	}

	public String getExtBannertype() {
		return this.extBannertype;
	}

	public void setExtBannertype(String extBannertype) {
		this.extBannertype = extBannertype;
	}

	public String getPrepend() {
		return this.prepend;
	}

	public void setPrepend(String prepend) {
		this.prepend = prepend;
	}

}
