package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * BannerVastElement generated by hbm2java
 */
public class BannerVastElement implements java.io.Serializable {

	private BannerVastElementId id;

	public BannerVastElement() {
	}

	public BannerVastElement(BannerVastElementId id) {
		this.id = id;
	}

	public BannerVastElementId getId() {
		return this.id;
	}

	public void setId(BannerVastElementId id) {
		this.id = id;
	}

}
