package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Campaigns generated by hbm2java
 */
public class Campaigns implements java.io.Serializable {

	private Integer campaignid;

	private String campaignname;

	private int clientid;

	private Integer views;

	private Integer clicks;

	private Integer conversions;

	private int priority;

	private byte weight;

	private int targetImpression;

	private int targetClick;

	private int targetConversion;

	private String anonymous;

	private Short companion;

	private String comments;

	private BigDecimal revenue;

	private Short revenueType;

	private Date updated;

	private int block;

	private int capping;

	private int sessionCapping;

	private Integer anCampaignId;

	private Integer asCampaignId;

	private int status;

	private int anStatus;

	private int asRejectReason;

	private int hostedViews;

	private int hostedClicks;

	private int viewwindow;

	private int clickwindow;

	private BigDecimal ecpm;

	private int minImpressions;

	private byte ecpmEnabled;

	private Date activateTime;

	private Date expireTime;

	private byte type;

	private byte showCappedNoCookie;

	public Campaigns() {
	}

	public Campaigns(String campaignname, int clientid, int priority, byte weight, int targetImpression, int targetClick, int targetConversion, String anonymous, Date updated, int block,
			int capping, int sessionCapping, int status, int anStatus, int asRejectReason, int hostedViews, int hostedClicks, int viewwindow, int clickwindow, int minImpressions, byte ecpmEnabled,
			byte type, byte showCappedNoCookie) {
		this.campaignname = campaignname;
		this.clientid = clientid;
		this.priority = priority;
		this.weight = weight;
		this.targetImpression = targetImpression;
		this.targetClick = targetClick;
		this.targetConversion = targetConversion;
		this.anonymous = anonymous;
		this.updated = updated;
		this.block = block;
		this.capping = capping;
		this.sessionCapping = sessionCapping;
		this.status = status;
		this.anStatus = anStatus;
		this.asRejectReason = asRejectReason;
		this.hostedViews = hostedViews;
		this.hostedClicks = hostedClicks;
		this.viewwindow = viewwindow;
		this.clickwindow = clickwindow;
		this.minImpressions = minImpressions;
		this.ecpmEnabled = ecpmEnabled;
		this.type = type;
		this.showCappedNoCookie = showCappedNoCookie;
	}

	public Campaigns(String campaignname, int clientid, Integer views, Integer clicks, Integer conversions, int priority, byte weight, int targetImpression, int targetClick, int targetConversion,
			String anonymous, Short companion, String comments, BigDecimal revenue, Short revenueType, Date updated, int block, int capping, int sessionCapping, Integer anCampaignId,
			Integer asCampaignId, int status, int anStatus, int asRejectReason, int hostedViews, int hostedClicks, int viewwindow, int clickwindow, BigDecimal ecpm, int minImpressions,
			byte ecpmEnabled, Date activateTime, Date expireTime, byte type, byte showCappedNoCookie) {
		this.campaignname = campaignname;
		this.clientid = clientid;
		this.views = views;
		this.clicks = clicks;
		this.conversions = conversions;
		this.priority = priority;
		this.weight = weight;
		this.targetImpression = targetImpression;
		this.targetClick = targetClick;
		this.targetConversion = targetConversion;
		this.anonymous = anonymous;
		this.companion = companion;
		this.comments = comments;
		this.revenue = revenue;
		this.revenueType = revenueType;
		this.updated = updated;
		this.block = block;
		this.capping = capping;
		this.sessionCapping = sessionCapping;
		this.anCampaignId = anCampaignId;
		this.asCampaignId = asCampaignId;
		this.status = status;
		this.anStatus = anStatus;
		this.asRejectReason = asRejectReason;
		this.hostedViews = hostedViews;
		this.hostedClicks = hostedClicks;
		this.viewwindow = viewwindow;
		this.clickwindow = clickwindow;
		this.ecpm = ecpm;
		this.minImpressions = minImpressions;
		this.ecpmEnabled = ecpmEnabled;
		this.activateTime = activateTime;
		this.expireTime = expireTime;
		this.type = type;
		this.showCappedNoCookie = showCappedNoCookie;
	}

	public Integer getCampaignid() {
		return this.campaignid;
	}

	public void setCampaignid(Integer campaignid) {
		this.campaignid = campaignid;
	}

	public String getCampaignname() {
		return this.campaignname;
	}

	public void setCampaignname(String campaignname) {
		this.campaignname = campaignname;
	}

	public int getClientid() {
		return this.clientid;
	}

	public void setClientid(int clientid) {
		this.clientid = clientid;
	}

	public Integer getViews() {
		return this.views;
	}

	public void setViews(Integer views) {
		this.views = views;
	}

	public Integer getClicks() {
		return this.clicks;
	}

	public void setClicks(Integer clicks) {
		this.clicks = clicks;
	}

	public Integer getConversions() {
		return this.conversions;
	}

	public void setConversions(Integer conversions) {
		this.conversions = conversions;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public byte getWeight() {
		return this.weight;
	}

	public void setWeight(byte weight) {
		this.weight = weight;
	}

	public int getTargetImpression() {
		return this.targetImpression;
	}

	public void setTargetImpression(int targetImpression) {
		this.targetImpression = targetImpression;
	}

	public int getTargetClick() {
		return this.targetClick;
	}

	public void setTargetClick(int targetClick) {
		this.targetClick = targetClick;
	}

	public int getTargetConversion() {
		return this.targetConversion;
	}

	public void setTargetConversion(int targetConversion) {
		this.targetConversion = targetConversion;
	}

	public String getAnonymous() {
		return this.anonymous;
	}

	public void setAnonymous(String anonymous) {
		this.anonymous = anonymous;
	}

	public Short getCompanion() {
		return this.companion;
	}

	public void setCompanion(Short companion) {
		this.companion = companion;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

	public Short getRevenueType() {
		return this.revenueType;
	}

	public void setRevenueType(Short revenueType) {
		this.revenueType = revenueType;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public int getBlock() {
		return this.block;
	}

	public void setBlock(int block) {
		this.block = block;
	}

	public int getCapping() {
		return this.capping;
	}

	public void setCapping(int capping) {
		this.capping = capping;
	}

	public int getSessionCapping() {
		return this.sessionCapping;
	}

	public void setSessionCapping(int sessionCapping) {
		this.sessionCapping = sessionCapping;
	}

	public Integer getAnCampaignId() {
		return this.anCampaignId;
	}

	public void setAnCampaignId(Integer anCampaignId) {
		this.anCampaignId = anCampaignId;
	}

	public Integer getAsCampaignId() {
		return this.asCampaignId;
	}

	public void setAsCampaignId(Integer asCampaignId) {
		this.asCampaignId = asCampaignId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getAnStatus() {
		return this.anStatus;
	}

	public void setAnStatus(int anStatus) {
		this.anStatus = anStatus;
	}

	public int getAsRejectReason() {
		return this.asRejectReason;
	}

	public void setAsRejectReason(int asRejectReason) {
		this.asRejectReason = asRejectReason;
	}

	public int getHostedViews() {
		return this.hostedViews;
	}

	public void setHostedViews(int hostedViews) {
		this.hostedViews = hostedViews;
	}

	public int getHostedClicks() {
		return this.hostedClicks;
	}

	public void setHostedClicks(int hostedClicks) {
		this.hostedClicks = hostedClicks;
	}

	public int getViewwindow() {
		return this.viewwindow;
	}

	public void setViewwindow(int viewwindow) {
		this.viewwindow = viewwindow;
	}

	public int getClickwindow() {
		return this.clickwindow;
	}

	public void setClickwindow(int clickwindow) {
		this.clickwindow = clickwindow;
	}

	public BigDecimal getEcpm() {
		return this.ecpm;
	}

	public void setEcpm(BigDecimal ecpm) {
		this.ecpm = ecpm;
	}

	public int getMinImpressions() {
		return this.minImpressions;
	}

	public void setMinImpressions(int minImpressions) {
		this.minImpressions = minImpressions;
	}

	public byte getEcpmEnabled() {
		return this.ecpmEnabled;
	}

	public void setEcpmEnabled(byte ecpmEnabled) {
		this.ecpmEnabled = ecpmEnabled;
	}

	public Date getActivateTime() {
		return this.activateTime;
	}

	public void setActivateTime(Date activateTime) {
		this.activateTime = activateTime;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	public byte getShowCappedNoCookie() {
		return this.showCappedNoCookie;
	}

	public void setShowCappedNoCookie(byte showCappedNoCookie) {
		this.showCappedNoCookie = showCappedNoCookie;
	}

}
