package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Channel generated by hbm2java
 */
public class Channel implements java.io.Serializable {

	private Integer channelid;

	private int agencyid;

	private int affiliateid;

	private String name;

	private String description;

	private String compiledlimitation;

	private String aclPlugins;

	private Short active;

	private String comments;

	private Date updated;

	private Date aclsUpdated;

	public Channel() {
	}

	public Channel(int agencyid, int affiliateid, String compiledlimitation, Date updated, Date aclsUpdated) {
		this.agencyid = agencyid;
		this.affiliateid = affiliateid;
		this.compiledlimitation = compiledlimitation;
		this.updated = updated;
		this.aclsUpdated = aclsUpdated;
	}

	public Channel(int agencyid, int affiliateid, String name, String description, String compiledlimitation, String aclPlugins, Short active, String comments, Date updated, Date aclsUpdated) {
		this.agencyid = agencyid;
		this.affiliateid = affiliateid;
		this.name = name;
		this.description = description;
		this.compiledlimitation = compiledlimitation;
		this.aclPlugins = aclPlugins;
		this.active = active;
		this.comments = comments;
		this.updated = updated;
		this.aclsUpdated = aclsUpdated;
	}

	public Integer getChannelid() {
		return this.channelid;
	}

	public void setChannelid(Integer channelid) {
		this.channelid = channelid;
	}

	public int getAgencyid() {
		return this.agencyid;
	}

	public void setAgencyid(int agencyid) {
		this.agencyid = agencyid;
	}

	public int getAffiliateid() {
		return this.affiliateid;
	}

	public void setAffiliateid(int affiliateid) {
		this.affiliateid = affiliateid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCompiledlimitation() {
		return this.compiledlimitation;
	}

	public void setCompiledlimitation(String compiledlimitation) {
		this.compiledlimitation = compiledlimitation;
	}

	public String getAclPlugins() {
		return this.aclPlugins;
	}

	public void setAclPlugins(String aclPlugins) {
		this.aclPlugins = aclPlugins;
	}

	public Short getActive() {
		return this.active;
	}

	public void setActive(Short active) {
		this.active = active;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Date getAclsUpdated() {
		return this.aclsUpdated;
	}

	public void setAclsUpdated(Date aclsUpdated) {
		this.aclsUpdated = aclsUpdated;
	}

}
