package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private Integer clientid;

	private int agencyid;

	private String clientname;

	private String contact;

	private String email;

	private String report;

	private int reportinterval;

	private Date reportlastdate;

	private String reportdeactivate;

	private String comments;

	private Date updated;

	private Integer anAdnetworkId;

	private Integer asAdvertiserId;

	private Integer accountId;

	private boolean advertiserLimitation;

	private byte type;

	public Clients() {
	}

	public Clients(int agencyid, String clientname, String email, String report, int reportinterval, Date reportlastdate, String reportdeactivate, Date updated, boolean advertiserLimitation,
			byte type) {
		this.agencyid = agencyid;
		this.clientname = clientname;
		this.email = email;
		this.report = report;
		this.reportinterval = reportinterval;
		this.reportlastdate = reportlastdate;
		this.reportdeactivate = reportdeactivate;
		this.updated = updated;
		this.advertiserLimitation = advertiserLimitation;
		this.type = type;
	}

	public Clients(int agencyid, String clientname, String contact, String email, String report, int reportinterval, Date reportlastdate, String reportdeactivate, String comments, Date updated,
			Integer anAdnetworkId, Integer asAdvertiserId, Integer accountId, boolean advertiserLimitation, byte type) {
		this.agencyid = agencyid;
		this.clientname = clientname;
		this.contact = contact;
		this.email = email;
		this.report = report;
		this.reportinterval = reportinterval;
		this.reportlastdate = reportlastdate;
		this.reportdeactivate = reportdeactivate;
		this.comments = comments;
		this.updated = updated;
		this.anAdnetworkId = anAdnetworkId;
		this.asAdvertiserId = asAdvertiserId;
		this.accountId = accountId;
		this.advertiserLimitation = advertiserLimitation;
		this.type = type;
	}

	public Integer getClientid() {
		return this.clientid;
	}

	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	public int getAgencyid() {
		return this.agencyid;
	}

	public void setAgencyid(int agencyid) {
		this.agencyid = agencyid;
	}

	public String getClientname() {
		return this.clientname;
	}

	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

	public int getReportinterval() {
		return this.reportinterval;
	}

	public void setReportinterval(int reportinterval) {
		this.reportinterval = reportinterval;
	}

	public Date getReportlastdate() {
		return this.reportlastdate;
	}

	public void setReportlastdate(Date reportlastdate) {
		this.reportlastdate = reportlastdate;
	}

	public String getReportdeactivate() {
		return this.reportdeactivate;
	}

	public void setReportdeactivate(String reportdeactivate) {
		this.reportdeactivate = reportdeactivate;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Integer getAnAdnetworkId() {
		return this.anAdnetworkId;
	}

	public void setAnAdnetworkId(Integer anAdnetworkId) {
		this.anAdnetworkId = anAdnetworkId;
	}

	public Integer getAsAdvertiserId() {
		return this.asAdvertiserId;
	}

	public void setAsAdvertiserId(Integer asAdvertiserId) {
		this.asAdvertiserId = asAdvertiserId;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public boolean isAdvertiserLimitation() {
		return this.advertiserLimitation;
	}

	public void setAdvertiserLimitation(boolean advertiserLimitation) {
		this.advertiserLimitation = advertiserLimitation;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

}
