package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataIntermediateAdConnection generated by hbm2java
 */
public class DataIntermediateAdConnection implements java.io.Serializable {

	private Long dataIntermediateAdConnectionId;

	private String serverRawIp;

	private long serverRawTrackerImpressionId;

	private String viewerId;

	private String viewerSessionId;

	private Date trackerDateTime;

	private Date connectionDateTime;

	private int trackerId;

	private int adId;

	private int creativeId;

	private int zoneId;

	private String trackerChannel;

	private String connectionChannel;

	private String trackerChannelIds;

	private String connectionChannelIds;

	private String trackerLanguage;

	private String connectionLanguage;

	private String trackerIpAddress;

	private String connectionIpAddress;

	private String trackerHostName;

	private String connectionHostName;

	private String trackerCountry;

	private String connectionCountry;

	private Integer trackerHttps;

	private Integer connectionHttps;

	private String trackerDomain;

	private String connectionDomain;

	private String trackerPage;

	private String connectionPage;

	private String trackerQuery;

	private String connectionQuery;

	private String trackerReferer;

	private String connectionReferer;

	private String trackerSearchTerm;

	private String connectionSearchTerm;

	private String trackerUserAgent;

	private String connectionUserAgent;

	private String trackerOs;

	private String connectionOs;

	private String trackerBrowser;

	private String connectionBrowser;

	private Integer connectionAction;

	private Integer connectionWindow;

	private int connectionStatus;

	private boolean insideWindow;

	private String comments;

	private Date updated;

	public DataIntermediateAdConnection() {
	}

	public DataIntermediateAdConnection(String serverRawIp, long serverRawTrackerImpressionId, Date trackerDateTime, int trackerId, int adId, int creativeId, int zoneId, int connectionStatus,
			boolean insideWindow, Date updated) {
		this.serverRawIp = serverRawIp;
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
		this.trackerDateTime = trackerDateTime;
		this.trackerId = trackerId;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.connectionStatus = connectionStatus;
		this.insideWindow = insideWindow;
		this.updated = updated;
	}

	public DataIntermediateAdConnection(String serverRawIp, long serverRawTrackerImpressionId, String viewerId, String viewerSessionId, Date trackerDateTime, Date connectionDateTime, int trackerId,
			int adId, int creativeId, int zoneId, String trackerChannel, String connectionChannel, String trackerChannelIds, String connectionChannelIds, String trackerLanguage,
			String connectionLanguage, String trackerIpAddress, String connectionIpAddress, String trackerHostName, String connectionHostName, String trackerCountry, String connectionCountry,
			Integer trackerHttps, Integer connectionHttps, String trackerDomain, String connectionDomain, String trackerPage, String connectionPage, String trackerQuery, String connectionQuery,
			String trackerReferer, String connectionReferer, String trackerSearchTerm, String connectionSearchTerm, String trackerUserAgent, String connectionUserAgent, String trackerOs,
			String connectionOs, String trackerBrowser, String connectionBrowser, Integer connectionAction, Integer connectionWindow, int connectionStatus, boolean insideWindow, String comments,
			Date updated) {
		this.serverRawIp = serverRawIp;
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
		this.viewerId = viewerId;
		this.viewerSessionId = viewerSessionId;
		this.trackerDateTime = trackerDateTime;
		this.connectionDateTime = connectionDateTime;
		this.trackerId = trackerId;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.trackerChannel = trackerChannel;
		this.connectionChannel = connectionChannel;
		this.trackerChannelIds = trackerChannelIds;
		this.connectionChannelIds = connectionChannelIds;
		this.trackerLanguage = trackerLanguage;
		this.connectionLanguage = connectionLanguage;
		this.trackerIpAddress = trackerIpAddress;
		this.connectionIpAddress = connectionIpAddress;
		this.trackerHostName = trackerHostName;
		this.connectionHostName = connectionHostName;
		this.trackerCountry = trackerCountry;
		this.connectionCountry = connectionCountry;
		this.trackerHttps = trackerHttps;
		this.connectionHttps = connectionHttps;
		this.trackerDomain = trackerDomain;
		this.connectionDomain = connectionDomain;
		this.trackerPage = trackerPage;
		this.connectionPage = connectionPage;
		this.trackerQuery = trackerQuery;
		this.connectionQuery = connectionQuery;
		this.trackerReferer = trackerReferer;
		this.connectionReferer = connectionReferer;
		this.trackerSearchTerm = trackerSearchTerm;
		this.connectionSearchTerm = connectionSearchTerm;
		this.trackerUserAgent = trackerUserAgent;
		this.connectionUserAgent = connectionUserAgent;
		this.trackerOs = trackerOs;
		this.connectionOs = connectionOs;
		this.trackerBrowser = trackerBrowser;
		this.connectionBrowser = connectionBrowser;
		this.connectionAction = connectionAction;
		this.connectionWindow = connectionWindow;
		this.connectionStatus = connectionStatus;
		this.insideWindow = insideWindow;
		this.comments = comments;
		this.updated = updated;
	}

	public Long getDataIntermediateAdConnectionId() {
		return this.dataIntermediateAdConnectionId;
	}

	public void setDataIntermediateAdConnectionId(Long dataIntermediateAdConnectionId) {
		this.dataIntermediateAdConnectionId = dataIntermediateAdConnectionId;
	}

	public String getServerRawIp() {
		return this.serverRawIp;
	}

	public void setServerRawIp(String serverRawIp) {
		this.serverRawIp = serverRawIp;
	}

	public long getServerRawTrackerImpressionId() {
		return this.serverRawTrackerImpressionId;
	}

	public void setServerRawTrackerImpressionId(long serverRawTrackerImpressionId) {
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
	}

	public String getViewerId() {
		return this.viewerId;
	}

	public void setViewerId(String viewerId) {
		this.viewerId = viewerId;
	}

	public String getViewerSessionId() {
		return this.viewerSessionId;
	}

	public void setViewerSessionId(String viewerSessionId) {
		this.viewerSessionId = viewerSessionId;
	}

	public Date getTrackerDateTime() {
		return this.trackerDateTime;
	}

	public void setTrackerDateTime(Date trackerDateTime) {
		this.trackerDateTime = trackerDateTime;
	}

	public Date getConnectionDateTime() {
		return this.connectionDateTime;
	}

	public void setConnectionDateTime(Date connectionDateTime) {
		this.connectionDateTime = connectionDateTime;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

	public int getCreativeId() {
		return this.creativeId;
	}

	public void setCreativeId(int creativeId) {
		this.creativeId = creativeId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getTrackerChannel() {
		return this.trackerChannel;
	}

	public void setTrackerChannel(String trackerChannel) {
		this.trackerChannel = trackerChannel;
	}

	public String getConnectionChannel() {
		return this.connectionChannel;
	}

	public void setConnectionChannel(String connectionChannel) {
		this.connectionChannel = connectionChannel;
	}

	public String getTrackerChannelIds() {
		return this.trackerChannelIds;
	}

	public void setTrackerChannelIds(String trackerChannelIds) {
		this.trackerChannelIds = trackerChannelIds;
	}

	public String getConnectionChannelIds() {
		return this.connectionChannelIds;
	}

	public void setConnectionChannelIds(String connectionChannelIds) {
		this.connectionChannelIds = connectionChannelIds;
	}

	public String getTrackerLanguage() {
		return this.trackerLanguage;
	}

	public void setTrackerLanguage(String trackerLanguage) {
		this.trackerLanguage = trackerLanguage;
	}

	public String getConnectionLanguage() {
		return this.connectionLanguage;
	}

	public void setConnectionLanguage(String connectionLanguage) {
		this.connectionLanguage = connectionLanguage;
	}

	public String getTrackerIpAddress() {
		return this.trackerIpAddress;
	}

	public void setTrackerIpAddress(String trackerIpAddress) {
		this.trackerIpAddress = trackerIpAddress;
	}

	public String getConnectionIpAddress() {
		return this.connectionIpAddress;
	}

	public void setConnectionIpAddress(String connectionIpAddress) {
		this.connectionIpAddress = connectionIpAddress;
	}

	public String getTrackerHostName() {
		return this.trackerHostName;
	}

	public void setTrackerHostName(String trackerHostName) {
		this.trackerHostName = trackerHostName;
	}

	public String getConnectionHostName() {
		return this.connectionHostName;
	}

	public void setConnectionHostName(String connectionHostName) {
		this.connectionHostName = connectionHostName;
	}

	public String getTrackerCountry() {
		return this.trackerCountry;
	}

	public void setTrackerCountry(String trackerCountry) {
		this.trackerCountry = trackerCountry;
	}

	public String getConnectionCountry() {
		return this.connectionCountry;
	}

	public void setConnectionCountry(String connectionCountry) {
		this.connectionCountry = connectionCountry;
	}

	public Integer getTrackerHttps() {
		return this.trackerHttps;
	}

	public void setTrackerHttps(Integer trackerHttps) {
		this.trackerHttps = trackerHttps;
	}

	public Integer getConnectionHttps() {
		return this.connectionHttps;
	}

	public void setConnectionHttps(Integer connectionHttps) {
		this.connectionHttps = connectionHttps;
	}

	public String getTrackerDomain() {
		return this.trackerDomain;
	}

	public void setTrackerDomain(String trackerDomain) {
		this.trackerDomain = trackerDomain;
	}

	public String getConnectionDomain() {
		return this.connectionDomain;
	}

	public void setConnectionDomain(String connectionDomain) {
		this.connectionDomain = connectionDomain;
	}

	public String getTrackerPage() {
		return this.trackerPage;
	}

	public void setTrackerPage(String trackerPage) {
		this.trackerPage = trackerPage;
	}

	public String getConnectionPage() {
		return this.connectionPage;
	}

	public void setConnectionPage(String connectionPage) {
		this.connectionPage = connectionPage;
	}

	public String getTrackerQuery() {
		return this.trackerQuery;
	}

	public void setTrackerQuery(String trackerQuery) {
		this.trackerQuery = trackerQuery;
	}

	public String getConnectionQuery() {
		return this.connectionQuery;
	}

	public void setConnectionQuery(String connectionQuery) {
		this.connectionQuery = connectionQuery;
	}

	public String getTrackerReferer() {
		return this.trackerReferer;
	}

	public void setTrackerReferer(String trackerReferer) {
		this.trackerReferer = trackerReferer;
	}

	public String getConnectionReferer() {
		return this.connectionReferer;
	}

	public void setConnectionReferer(String connectionReferer) {
		this.connectionReferer = connectionReferer;
	}

	public String getTrackerSearchTerm() {
		return this.trackerSearchTerm;
	}

	public void setTrackerSearchTerm(String trackerSearchTerm) {
		this.trackerSearchTerm = trackerSearchTerm;
	}

	public String getConnectionSearchTerm() {
		return this.connectionSearchTerm;
	}

	public void setConnectionSearchTerm(String connectionSearchTerm) {
		this.connectionSearchTerm = connectionSearchTerm;
	}

	public String getTrackerUserAgent() {
		return this.trackerUserAgent;
	}

	public void setTrackerUserAgent(String trackerUserAgent) {
		this.trackerUserAgent = trackerUserAgent;
	}

	public String getConnectionUserAgent() {
		return this.connectionUserAgent;
	}

	public void setConnectionUserAgent(String connectionUserAgent) {
		this.connectionUserAgent = connectionUserAgent;
	}

	public String getTrackerOs() {
		return this.trackerOs;
	}

	public void setTrackerOs(String trackerOs) {
		this.trackerOs = trackerOs;
	}

	public String getConnectionOs() {
		return this.connectionOs;
	}

	public void setConnectionOs(String connectionOs) {
		this.connectionOs = connectionOs;
	}

	public String getTrackerBrowser() {
		return this.trackerBrowser;
	}

	public void setTrackerBrowser(String trackerBrowser) {
		this.trackerBrowser = trackerBrowser;
	}

	public String getConnectionBrowser() {
		return this.connectionBrowser;
	}

	public void setConnectionBrowser(String connectionBrowser) {
		this.connectionBrowser = connectionBrowser;
	}

	public Integer getConnectionAction() {
		return this.connectionAction;
	}

	public void setConnectionAction(Integer connectionAction) {
		this.connectionAction = connectionAction;
	}

	public Integer getConnectionWindow() {
		return this.connectionWindow;
	}

	public void setConnectionWindow(Integer connectionWindow) {
		this.connectionWindow = connectionWindow;
	}

	public int getConnectionStatus() {
		return this.connectionStatus;
	}

	public void setConnectionStatus(int connectionStatus) {
		this.connectionStatus = connectionStatus;
	}

	public boolean isInsideWindow() {
		return this.insideWindow;
	}

	public void setInsideWindow(boolean insideWindow) {
		this.insideWindow = insideWindow;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
