package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DataSummaryAdHourly generated by hbm2java
 */
public class DataSummaryAdHourly implements java.io.Serializable {

	private Long dataSummaryAdHourlyId;

	private Date dateTime;

	private int adId;

	private int creativeId;

	private int zoneId;

	private int requests;

	private int impressions;

	private int clicks;

	private int conversions;

	private BigDecimal totalBasketValue;

	private Integer totalNumItems;

	private BigDecimal totalRevenue;

	private BigDecimal totalCost;

	private BigDecimal totalTechcost;

	private Date updated;

	public DataSummaryAdHourly() {
	}

	public DataSummaryAdHourly(Date dateTime, int adId, int creativeId, int zoneId, int requests, int impressions, int clicks, int conversions, Date updated) {
		this.dateTime = dateTime;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.requests = requests;
		this.impressions = impressions;
		this.clicks = clicks;
		this.conversions = conversions;
		this.updated = updated;
	}

	public DataSummaryAdHourly(Date dateTime, int adId, int creativeId, int zoneId, int requests, int impressions, int clicks, int conversions, BigDecimal totalBasketValue, Integer totalNumItems,
			BigDecimal totalRevenue, BigDecimal totalCost, BigDecimal totalTechcost, Date updated) {
		this.dateTime = dateTime;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.requests = requests;
		this.impressions = impressions;
		this.clicks = clicks;
		this.conversions = conversions;
		this.totalBasketValue = totalBasketValue;
		this.totalNumItems = totalNumItems;
		this.totalRevenue = totalRevenue;
		this.totalCost = totalCost;
		this.totalTechcost = totalTechcost;
		this.updated = updated;
	}

	public Long getDataSummaryAdHourlyId() {
		return this.dataSummaryAdHourlyId;
	}

	public void setDataSummaryAdHourlyId(Long dataSummaryAdHourlyId) {
		this.dataSummaryAdHourlyId = dataSummaryAdHourlyId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

	public int getCreativeId() {
		return this.creativeId;
	}

	public void setCreativeId(int creativeId) {
		this.creativeId = creativeId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public int getRequests() {
		return this.requests;
	}

	public void setRequests(int requests) {
		this.requests = requests;
	}

	public int getImpressions() {
		return this.impressions;
	}

	public void setImpressions(int impressions) {
		this.impressions = impressions;
	}

	public int getClicks() {
		return this.clicks;
	}

	public void setClicks(int clicks) {
		this.clicks = clicks;
	}

	public int getConversions() {
		return this.conversions;
	}

	public void setConversions(int conversions) {
		this.conversions = conversions;
	}

	public BigDecimal getTotalBasketValue() {
		return this.totalBasketValue;
	}

	public void setTotalBasketValue(BigDecimal totalBasketValue) {
		this.totalBasketValue = totalBasketValue;
	}

	public Integer getTotalNumItems() {
		return this.totalNumItems;
	}

	public void setTotalNumItems(Integer totalNumItems) {
		this.totalNumItems = totalNumItems;
	}

	public BigDecimal getTotalRevenue() {
		return this.totalRevenue;
	}

	public void setTotalRevenue(BigDecimal totalRevenue) {
		this.totalRevenue = totalRevenue;
	}

	public BigDecimal getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	public BigDecimal getTotalTechcost() {
		return this.totalTechcost;
	}

	public void setTotalTechcost(BigDecimal totalTechcost) {
		this.totalTechcost = totalTechcost;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
