package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataRawAdImpression generated by hbm2java
 */
public class DataRawAdImpression implements java.io.Serializable {

	private DataRawAdImpressionId id;

	public DataRawAdImpression() {
	}

	public DataRawAdImpression(DataRawAdImpressionId id) {
		this.id = id;
	}

	public DataRawAdImpressionId getId() {
		return this.id;
	}

	public void setId(DataRawAdImpressionId id) {
		this.id = id;
	}

}
