package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataBktAVar generated by hbm2java
 */
public class DataBktAVar implements java.io.Serializable {

	private DataBktAVarId id;

	private String value;

	private Date dateTime;

	public DataBktAVar() {
	}

	public DataBktAVar(DataBktAVarId id, Date dateTime) {
		this.id = id;
		this.dateTime = dateTime;
	}

	public DataBktAVar(DataBktAVarId id, String value, Date dateTime) {
		this.id = id;
		this.value = value;
		this.dateTime = dateTime;
	}

	public DataBktAVarId getId() {
		return this.id;
	}

	public void setId(DataBktAVarId id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
