package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataBktA generated by hbm2java
 */
public class DataBktA implements java.io.Serializable {

	private DataBktAId id;

	private int trackerId;

	private Date dateTime;

	private Date actionDateTime;

	private int creativeId;

	private int zoneId;

	private String ipAddress;

	private Integer action;

	private Integer window;

	private Integer status;

	public DataBktA() {
	}

	public DataBktA(DataBktAId id, int trackerId, Date dateTime, Date actionDateTime, int creativeId, int zoneId, String ipAddress) {
		this.id = id;
		this.trackerId = trackerId;
		this.dateTime = dateTime;
		this.actionDateTime = actionDateTime;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.ipAddress = ipAddress;
	}

	public DataBktA(DataBktAId id, int trackerId, Date dateTime, Date actionDateTime, int creativeId, int zoneId, String ipAddress, Integer action, Integer window, Integer status) {
		this.id = id;
		this.trackerId = trackerId;
		this.dateTime = dateTime;
		this.actionDateTime = actionDateTime;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.ipAddress = ipAddress;
		this.action = action;
		this.window = window;
		this.status = status;
	}

	public DataBktAId getId() {
		return this.id;
	}

	public void setId(DataBktAId id) {
		this.id = id;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Date getActionDateTime() {
		return this.actionDateTime;
	}

	public void setActionDateTime(Date actionDateTime) {
		this.actionDateTime = actionDateTime;
	}

	public int getCreativeId() {
		return this.creativeId;
	}

	public void setCreativeId(int creativeId) {
		this.creativeId = creativeId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Integer getAction() {
		return this.action;
	}

	public void setAction(Integer action) {
		this.action = action;
	}

	public Integer getWindow() {
		return this.window;
	}

	public void setWindow(Integer window) {
		this.window = window;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
