package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataBktVastEId generated by hbm2java
 */
public class DataBktVastEId implements java.io.Serializable {

	private Date intervalStart;

	private int creativeId;

	private int zoneId;

	private int vastEventId;

	public DataBktVastEId() {
	}

	public DataBktVastEId(Date intervalStart, int creativeId, int zoneId, int vastEventId) {
		this.intervalStart = intervalStart;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.vastEventId = vastEventId;
	}

	public Date getIntervalStart() {
		return this.intervalStart;
	}

	public void setIntervalStart(Date intervalStart) {
		this.intervalStart = intervalStart;
	}

	public int getCreativeId() {
		return this.creativeId;
	}

	public void setCreativeId(int creativeId) {
		this.creativeId = creativeId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public int getVastEventId() {
		return this.vastEventId;
	}

	public void setVastEventId(int vastEventId) {
		this.vastEventId = vastEventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataBktVastEId))
			return false;
		DataBktVastEId castOther = (DataBktVastEId) other;

		return ((this.getIntervalStart() == castOther.getIntervalStart()) || (this.getIntervalStart() != null && castOther.getIntervalStart() != null && this.getIntervalStart().equals(
				castOther.getIntervalStart())))
				&& (this.getCreativeId() == castOther.getCreativeId()) && (this.getZoneId() == castOther.getZoneId()) && (this.getVastEventId() == castOther.getVastEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIntervalStart() == null ? 0 : this.getIntervalStart().hashCode());
		result = 37 * result + this.getCreativeId();
		result = 37 * result + this.getZoneId();
		result = 37 * result + this.getVastEventId();
		return result;
	}

}
