package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataRawTrackerVariableValue generated by hbm2java
 */
public class DataRawTrackerVariableValue implements java.io.Serializable {

	private DataRawTrackerVariableValueId id;

	private Date dateTime;

	private String value;

	public DataRawTrackerVariableValue() {
	}

	public DataRawTrackerVariableValue(DataRawTrackerVariableValueId id) {
		this.id = id;
	}

	public DataRawTrackerVariableValue(DataRawTrackerVariableValueId id, Date dateTime, String value) {
		this.id = id;
		this.dateTime = dateTime;
		this.value = value;
	}

	public DataRawTrackerVariableValueId getId() {
		return this.id;
	}

	public void setId(DataRawTrackerVariableValueId id) {
		this.id = id;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
