package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataRawAdClick generated by hbm2java
 */
public class DataRawAdClick implements java.io.Serializable {

	private DataRawAdClickId id;

	public DataRawAdClick() {
	}

	public DataRawAdClick(DataRawAdClickId id) {
		this.id = id;
	}

	public DataRawAdClickId getId() {
		return this.id;
	}

	public void setId(DataRawAdClickId id) {
		this.id = id;
	}

}
