package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DataRawAdClickId generated by hbm2java
 */
public class DataRawAdClickId implements java.io.Serializable {

	private String viewerId;

	private String viewerSessionId;

	private Date dateTime;

	private int adId;

	private int creativeId;

	private int zoneId;

	private String channel;

	private String channelIds;

	private String language;

	private String ipAddress;

	private String hostName;

	private String country;

	private Boolean https;

	private String domain;

	private String page;

	private String query;

	private String referer;

	private String searchTerm;

	private String userAgent;

	private String os;

	private String browser;

	private Boolean maxHttps;

	private String geoRegion;

	private String geoCity;

	private String geoPostalCode;

	private BigDecimal geoLatitude;

	private BigDecimal geoLongitude;

	private String geoDmaCode;

	private String geoAreaCode;

	private String geoOrganisation;

	private String geoNetspeed;

	private String geoContinent;

	public DataRawAdClickId() {
	}

	public DataRawAdClickId(Date dateTime, int adId, int creativeId, int zoneId) {
		this.dateTime = dateTime;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
	}

	public DataRawAdClickId(String viewerId, String viewerSessionId, Date dateTime, int adId, int creativeId, int zoneId, String channel, String channelIds, String language, String ipAddress,
			String hostName, String country, Boolean https, String domain, String page, String query, String referer, String searchTerm, String userAgent, String os, String browser, Boolean maxHttps,
			String geoRegion, String geoCity, String geoPostalCode, BigDecimal geoLatitude, BigDecimal geoLongitude, String geoDmaCode, String geoAreaCode, String geoOrganisation, String geoNetspeed,
			String geoContinent) {
		this.viewerId = viewerId;
		this.viewerSessionId = viewerSessionId;
		this.dateTime = dateTime;
		this.adId = adId;
		this.creativeId = creativeId;
		this.zoneId = zoneId;
		this.channel = channel;
		this.channelIds = channelIds;
		this.language = language;
		this.ipAddress = ipAddress;
		this.hostName = hostName;
		this.country = country;
		this.https = https;
		this.domain = domain;
		this.page = page;
		this.query = query;
		this.referer = referer;
		this.searchTerm = searchTerm;
		this.userAgent = userAgent;
		this.os = os;
		this.browser = browser;
		this.maxHttps = maxHttps;
		this.geoRegion = geoRegion;
		this.geoCity = geoCity;
		this.geoPostalCode = geoPostalCode;
		this.geoLatitude = geoLatitude;
		this.geoLongitude = geoLongitude;
		this.geoDmaCode = geoDmaCode;
		this.geoAreaCode = geoAreaCode;
		this.geoOrganisation = geoOrganisation;
		this.geoNetspeed = geoNetspeed;
		this.geoContinent = geoContinent;
	}

	public String getViewerId() {
		return this.viewerId;
	}

	public void setViewerId(String viewerId) {
		this.viewerId = viewerId;
	}

	public String getViewerSessionId() {
		return this.viewerSessionId;
	}

	public void setViewerSessionId(String viewerSessionId) {
		this.viewerSessionId = viewerSessionId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

	public int getCreativeId() {
		return this.creativeId;
	}

	public void setCreativeId(int creativeId) {
		this.creativeId = creativeId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getChannelIds() {
		return this.channelIds;
	}

	public void setChannelIds(String channelIds) {
		this.channelIds = channelIds;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Boolean getHttps() {
		return this.https;
	}

	public void setHttps(Boolean https) {
		this.https = https;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	public String getSearchTerm() {
		return this.searchTerm;
	}

	public void setSearchTerm(String searchTerm) {
		this.searchTerm = searchTerm;
	}

	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	public Boolean getMaxHttps() {
		return this.maxHttps;
	}

	public void setMaxHttps(Boolean maxHttps) {
		this.maxHttps = maxHttps;
	}

	public String getGeoRegion() {
		return this.geoRegion;
	}

	public void setGeoRegion(String geoRegion) {
		this.geoRegion = geoRegion;
	}

	public String getGeoCity() {
		return this.geoCity;
	}

	public void setGeoCity(String geoCity) {
		this.geoCity = geoCity;
	}

	public String getGeoPostalCode() {
		return this.geoPostalCode;
	}

	public void setGeoPostalCode(String geoPostalCode) {
		this.geoPostalCode = geoPostalCode;
	}

	public BigDecimal getGeoLatitude() {
		return this.geoLatitude;
	}

	public void setGeoLatitude(BigDecimal geoLatitude) {
		this.geoLatitude = geoLatitude;
	}

	public BigDecimal getGeoLongitude() {
		return this.geoLongitude;
	}

	public void setGeoLongitude(BigDecimal geoLongitude) {
		this.geoLongitude = geoLongitude;
	}

	public String getGeoDmaCode() {
		return this.geoDmaCode;
	}

	public void setGeoDmaCode(String geoDmaCode) {
		this.geoDmaCode = geoDmaCode;
	}

	public String getGeoAreaCode() {
		return this.geoAreaCode;
	}

	public void setGeoAreaCode(String geoAreaCode) {
		this.geoAreaCode = geoAreaCode;
	}

	public String getGeoOrganisation() {
		return this.geoOrganisation;
	}

	public void setGeoOrganisation(String geoOrganisation) {
		this.geoOrganisation = geoOrganisation;
	}

	public String getGeoNetspeed() {
		return this.geoNetspeed;
	}

	public void setGeoNetspeed(String geoNetspeed) {
		this.geoNetspeed = geoNetspeed;
	}

	public String getGeoContinent() {
		return this.geoContinent;
	}

	public void setGeoContinent(String geoContinent) {
		this.geoContinent = geoContinent;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataRawAdClickId))
			return false;
		DataRawAdClickId castOther = (DataRawAdClickId) other;

		return ((this.getViewerId() == castOther.getViewerId()) || (this.getViewerId() != null && castOther.getViewerId() != null && this.getViewerId().equals(castOther.getViewerId())))
				&& ((this.getViewerSessionId() == castOther.getViewerSessionId()) || (this.getViewerSessionId() != null && castOther.getViewerSessionId() != null && this.getViewerSessionId().equals(
						castOther.getViewerSessionId())))
				&& ((this.getDateTime() == castOther.getDateTime()) || (this.getDateTime() != null && castOther.getDateTime() != null && this.getDateTime().equals(castOther.getDateTime())))
				&& (this.getAdId() == castOther.getAdId())
				&& (this.getCreativeId() == castOther.getCreativeId())
				&& (this.getZoneId() == castOther.getZoneId())
				&& ((this.getChannel() == castOther.getChannel()) || (this.getChannel() != null && castOther.getChannel() != null && this.getChannel().equals(castOther.getChannel())))
				&& ((this.getChannelIds() == castOther.getChannelIds()) || (this.getChannelIds() != null && castOther.getChannelIds() != null && this.getChannelIds().equals(castOther.getChannelIds())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null && castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getIpAddress() == castOther.getIpAddress()) || (this.getIpAddress() != null && castOther.getIpAddress() != null && this.getIpAddress().equals(castOther.getIpAddress())))
				&& ((this.getHostName() == castOther.getHostName()) || (this.getHostName() != null && castOther.getHostName() != null && this.getHostName().equals(castOther.getHostName())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null && castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getHttps() == castOther.getHttps()) || (this.getHttps() != null && castOther.getHttps() != null && this.getHttps().equals(castOther.getHttps())))
				&& ((this.getDomain() == castOther.getDomain()) || (this.getDomain() != null && castOther.getDomain() != null && this.getDomain().equals(castOther.getDomain())))
				&& ((this.getPage() == castOther.getPage()) || (this.getPage() != null && castOther.getPage() != null && this.getPage().equals(castOther.getPage())))
				&& ((this.getQuery() == castOther.getQuery()) || (this.getQuery() != null && castOther.getQuery() != null && this.getQuery().equals(castOther.getQuery())))
				&& ((this.getReferer() == castOther.getReferer()) || (this.getReferer() != null && castOther.getReferer() != null && this.getReferer().equals(castOther.getReferer())))
				&& ((this.getSearchTerm() == castOther.getSearchTerm()) || (this.getSearchTerm() != null && castOther.getSearchTerm() != null && this.getSearchTerm().equals(castOther.getSearchTerm())))
				&& ((this.getUserAgent() == castOther.getUserAgent()) || (this.getUserAgent() != null && castOther.getUserAgent() != null && this.getUserAgent().equals(castOther.getUserAgent())))
				&& ((this.getOs() == castOther.getOs()) || (this.getOs() != null && castOther.getOs() != null && this.getOs().equals(castOther.getOs())))
				&& ((this.getBrowser() == castOther.getBrowser()) || (this.getBrowser() != null && castOther.getBrowser() != null && this.getBrowser().equals(castOther.getBrowser())))
				&& ((this.getMaxHttps() == castOther.getMaxHttps()) || (this.getMaxHttps() != null && castOther.getMaxHttps() != null && this.getMaxHttps().equals(castOther.getMaxHttps())))
				&& ((this.getGeoRegion() == castOther.getGeoRegion()) || (this.getGeoRegion() != null && castOther.getGeoRegion() != null && this.getGeoRegion().equals(castOther.getGeoRegion())))
				&& ((this.getGeoCity() == castOther.getGeoCity()) || (this.getGeoCity() != null && castOther.getGeoCity() != null && this.getGeoCity().equals(castOther.getGeoCity())))
				&& ((this.getGeoPostalCode() == castOther.getGeoPostalCode()) || (this.getGeoPostalCode() != null && castOther.getGeoPostalCode() != null && this.getGeoPostalCode().equals(
						castOther.getGeoPostalCode())))
				&& ((this.getGeoLatitude() == castOther.getGeoLatitude()) || (this.getGeoLatitude() != null && castOther.getGeoLatitude() != null && this.getGeoLatitude().equals(
						castOther.getGeoLatitude())))
				&& ((this.getGeoLongitude() == castOther.getGeoLongitude()) || (this.getGeoLongitude() != null && castOther.getGeoLongitude() != null && this.getGeoLongitude().equals(
						castOther.getGeoLongitude())))
				&& ((this.getGeoDmaCode() == castOther.getGeoDmaCode()) || (this.getGeoDmaCode() != null && castOther.getGeoDmaCode() != null && this.getGeoDmaCode().equals(castOther.getGeoDmaCode())))
				&& ((this.getGeoAreaCode() == castOther.getGeoAreaCode()) || (this.getGeoAreaCode() != null && castOther.getGeoAreaCode() != null && this.getGeoAreaCode().equals(
						castOther.getGeoAreaCode())))
				&& ((this.getGeoOrganisation() == castOther.getGeoOrganisation()) || (this.getGeoOrganisation() != null && castOther.getGeoOrganisation() != null && this.getGeoOrganisation().equals(
						castOther.getGeoOrganisation())))
				&& ((this.getGeoNetspeed() == castOther.getGeoNetspeed()) || (this.getGeoNetspeed() != null && castOther.getGeoNetspeed() != null && this.getGeoNetspeed().equals(
						castOther.getGeoNetspeed())))
				&& ((this.getGeoContinent() == castOther.getGeoContinent()) || (this.getGeoContinent() != null && castOther.getGeoContinent() != null && this.getGeoContinent().equals(
						castOther.getGeoContinent())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getViewerId() == null ? 0 : this.getViewerId().hashCode());
		result = 37 * result + (getViewerSessionId() == null ? 0 : this.getViewerSessionId().hashCode());
		result = 37 * result + (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		result = 37 * result + this.getAdId();
		result = 37 * result + this.getCreativeId();
		result = 37 * result + this.getZoneId();
		result = 37 * result + (getChannel() == null ? 0 : this.getChannel().hashCode());
		result = 37 * result + (getChannelIds() == null ? 0 : this.getChannelIds().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result + (getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37 * result + (getHostName() == null ? 0 : this.getHostName().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getHttps() == null ? 0 : this.getHttps().hashCode());
		result = 37 * result + (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result + (getPage() == null ? 0 : this.getPage().hashCode());
		result = 37 * result + (getQuery() == null ? 0 : this.getQuery().hashCode());
		result = 37 * result + (getReferer() == null ? 0 : this.getReferer().hashCode());
		result = 37 * result + (getSearchTerm() == null ? 0 : this.getSearchTerm().hashCode());
		result = 37 * result + (getUserAgent() == null ? 0 : this.getUserAgent().hashCode());
		result = 37 * result + (getOs() == null ? 0 : this.getOs().hashCode());
		result = 37 * result + (getBrowser() == null ? 0 : this.getBrowser().hashCode());
		result = 37 * result + (getMaxHttps() == null ? 0 : this.getMaxHttps().hashCode());
		result = 37 * result + (getGeoRegion() == null ? 0 : this.getGeoRegion().hashCode());
		result = 37 * result + (getGeoCity() == null ? 0 : this.getGeoCity().hashCode());
		result = 37 * result + (getGeoPostalCode() == null ? 0 : this.getGeoPostalCode().hashCode());
		result = 37 * result + (getGeoLatitude() == null ? 0 : this.getGeoLatitude().hashCode());
		result = 37 * result + (getGeoLongitude() == null ? 0 : this.getGeoLongitude().hashCode());
		result = 37 * result + (getGeoDmaCode() == null ? 0 : this.getGeoDmaCode().hashCode());
		result = 37 * result + (getGeoAreaCode() == null ? 0 : this.getGeoAreaCode().hashCode());
		result = 37 * result + (getGeoOrganisation() == null ? 0 : this.getGeoOrganisation().hashCode());
		result = 37 * result + (getGeoNetspeed() == null ? 0 : this.getGeoNetspeed().hashCode());
		result = 37 * result + (getGeoContinent() == null ? 0 : this.getGeoContinent().hashCode());
		return result;
	}

}
