package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DatabaseAction generated by hbm2java
 */
public class DatabaseAction implements java.io.Serializable {

	private Integer databaseActionId;

	private int version;

	private Integer upgradeActionId;

	private String schemaName;

	private int timing;

	private int action;

	private String info1;

	private String info2;

	private String tablename;

	private String tablenameBackup;

	private String tableBackupSchema;

	private Date updated;

	public DatabaseAction() {
	}

	public DatabaseAction(int timing, int action) {
		this.timing = timing;
		this.action = action;
	}

	public DatabaseAction(Integer upgradeActionId, String schemaName, int timing, int action, String info1, String info2, String tablename, String tablenameBackup, String tableBackupSchema,
			Date updated) {
		this.upgradeActionId = upgradeActionId;
		this.schemaName = schemaName;
		this.timing = timing;
		this.action = action;
		this.info1 = info1;
		this.info2 = info2;
		this.tablename = tablename;
		this.tablenameBackup = tablenameBackup;
		this.tableBackupSchema = tableBackupSchema;
		this.updated = updated;
	}

	public Integer getDatabaseActionId() {
		return this.databaseActionId;
	}

	public void setDatabaseActionId(Integer databaseActionId) {
		this.databaseActionId = databaseActionId;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public Integer getUpgradeActionId() {
		return this.upgradeActionId;
	}

	public void setUpgradeActionId(Integer upgradeActionId) {
		this.upgradeActionId = upgradeActionId;
	}

	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	public int getTiming() {
		return this.timing;
	}

	public void setTiming(int timing) {
		this.timing = timing;
	}

	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

	public String getInfo1() {
		return this.info1;
	}

	public void setInfo1(String info1) {
		this.info1 = info1;
	}

	public String getInfo2() {
		return this.info2;
	}

	public void setInfo2(String info2) {
		this.info2 = info2;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getTablenameBackup() {
		return this.tablenameBackup;
	}

	public void setTablenameBackup(String tablenameBackup) {
		this.tablenameBackup = tablenameBackup;
	}

	public String getTableBackupSchema() {
		return this.tableBackupSchema;
	}

	public void setTableBackupSchema(String tableBackupSchema) {
		this.tableBackupSchema = tableBackupSchema;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
