package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * DataRawTrackerImpression generated by hbm2java
 */
public class DataRawTrackerImpression implements java.io.Serializable {

	private DataRawTrackerImpressionId id;

	private String viewerId;

	private String viewerSessionId;

	private Date dateTime;

	private int trackerId;

	private String channel;

	private String channelIds;

	private String language;

	private String ipAddress;

	private String hostName;

	private String country;

	private Integer https;

	private String domain;

	private String page;

	private String query;

	private String referer;

	private String searchTerm;

	private String userAgent;

	private String os;

	private String browser;

	private Integer maxHttps;

	private String geoRegion;

	private String geoCity;

	private String geoPostalCode;

	private BigDecimal geoLatitude;

	private BigDecimal geoLongitude;

	private String geoDmaCode;

	private String geoAreaCode;

	private String geoOrganisation;

	private String geoNetspeed;

	private String geoContinent;

	public DataRawTrackerImpression() {
	}

	public DataRawTrackerImpression(DataRawTrackerImpressionId id, String viewerId, Date dateTime, int trackerId) {
		this.id = id;
		this.viewerId = viewerId;
		this.dateTime = dateTime;
		this.trackerId = trackerId;
	}

	public DataRawTrackerImpression(DataRawTrackerImpressionId id, String viewerId, String viewerSessionId, Date dateTime, int trackerId, String channel, String channelIds, String language,
			String ipAddress, String hostName, String country, Integer https, String domain, String page, String query, String referer, String searchTerm, String userAgent, String os, String browser,
			Integer maxHttps, String geoRegion, String geoCity, String geoPostalCode, BigDecimal geoLatitude, BigDecimal geoLongitude, String geoDmaCode, String geoAreaCode, String geoOrganisation,
			String geoNetspeed, String geoContinent) {
		this.id = id;
		this.viewerId = viewerId;
		this.viewerSessionId = viewerSessionId;
		this.dateTime = dateTime;
		this.trackerId = trackerId;
		this.channel = channel;
		this.channelIds = channelIds;
		this.language = language;
		this.ipAddress = ipAddress;
		this.hostName = hostName;
		this.country = country;
		this.https = https;
		this.domain = domain;
		this.page = page;
		this.query = query;
		this.referer = referer;
		this.searchTerm = searchTerm;
		this.userAgent = userAgent;
		this.os = os;
		this.browser = browser;
		this.maxHttps = maxHttps;
		this.geoRegion = geoRegion;
		this.geoCity = geoCity;
		this.geoPostalCode = geoPostalCode;
		this.geoLatitude = geoLatitude;
		this.geoLongitude = geoLongitude;
		this.geoDmaCode = geoDmaCode;
		this.geoAreaCode = geoAreaCode;
		this.geoOrganisation = geoOrganisation;
		this.geoNetspeed = geoNetspeed;
		this.geoContinent = geoContinent;
	}

	public DataRawTrackerImpressionId getId() {
		return this.id;
	}

	public void setId(DataRawTrackerImpressionId id) {
		this.id = id;
	}

	public String getViewerId() {
		return this.viewerId;
	}

	public void setViewerId(String viewerId) {
		this.viewerId = viewerId;
	}

	public String getViewerSessionId() {
		return this.viewerSessionId;
	}

	public void setViewerSessionId(String viewerSessionId) {
		this.viewerSessionId = viewerSessionId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getChannelIds() {
		return this.channelIds;
	}

	public void setChannelIds(String channelIds) {
		this.channelIds = channelIds;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getHttps() {
		return this.https;
	}

	public void setHttps(Integer https) {
		this.https = https;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	public String getSearchTerm() {
		return this.searchTerm;
	}

	public void setSearchTerm(String searchTerm) {
		this.searchTerm = searchTerm;
	}

	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	public Integer getMaxHttps() {
		return this.maxHttps;
	}

	public void setMaxHttps(Integer maxHttps) {
		this.maxHttps = maxHttps;
	}

	public String getGeoRegion() {
		return this.geoRegion;
	}

	public void setGeoRegion(String geoRegion) {
		this.geoRegion = geoRegion;
	}

	public String getGeoCity() {
		return this.geoCity;
	}

	public void setGeoCity(String geoCity) {
		this.geoCity = geoCity;
	}

	public String getGeoPostalCode() {
		return this.geoPostalCode;
	}

	public void setGeoPostalCode(String geoPostalCode) {
		this.geoPostalCode = geoPostalCode;
	}

	public BigDecimal getGeoLatitude() {
		return this.geoLatitude;
	}

	public void setGeoLatitude(BigDecimal geoLatitude) {
		this.geoLatitude = geoLatitude;
	}

	public BigDecimal getGeoLongitude() {
		return this.geoLongitude;
	}

	public void setGeoLongitude(BigDecimal geoLongitude) {
		this.geoLongitude = geoLongitude;
	}

	public String getGeoDmaCode() {
		return this.geoDmaCode;
	}

	public void setGeoDmaCode(String geoDmaCode) {
		this.geoDmaCode = geoDmaCode;
	}

	public String getGeoAreaCode() {
		return this.geoAreaCode;
	}

	public void setGeoAreaCode(String geoAreaCode) {
		this.geoAreaCode = geoAreaCode;
	}

	public String getGeoOrganisation() {
		return this.geoOrganisation;
	}

	public void setGeoOrganisation(String geoOrganisation) {
		this.geoOrganisation = geoOrganisation;
	}

	public String getGeoNetspeed() {
		return this.geoNetspeed;
	}

	public void setGeoNetspeed(String geoNetspeed) {
		this.geoNetspeed = geoNetspeed;
	}

	public String getGeoContinent() {
		return this.geoContinent;
	}

	public void setGeoContinent(String geoContinent) {
		this.geoContinent = geoContinent;
	}

}
