package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataRawTrackerImpressionId generated by hbm2java
 */
public class DataRawTrackerImpressionId implements java.io.Serializable {

	private long serverRawTrackerImpressionId;

	private String serverRawIp;

	public DataRawTrackerImpressionId() {
	}

	public DataRawTrackerImpressionId(long serverRawTrackerImpressionId, String serverRawIp) {
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
		this.serverRawIp = serverRawIp;
	}

	public long getServerRawTrackerImpressionId() {
		return this.serverRawTrackerImpressionId;
	}

	public void setServerRawTrackerImpressionId(long serverRawTrackerImpressionId) {
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
	}

	public String getServerRawIp() {
		return this.serverRawIp;
	}

	public void setServerRawIp(String serverRawIp) {
		this.serverRawIp = serverRawIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataRawTrackerImpressionId))
			return false;
		DataRawTrackerImpressionId castOther = (DataRawTrackerImpressionId) other;

		return (this.getServerRawTrackerImpressionId() == castOther.getServerRawTrackerImpressionId())
				&& ((this.getServerRawIp() == castOther.getServerRawIp()) || (this.getServerRawIp() != null && castOther.getServerRawIp() != null && this.getServerRawIp().equals(
						castOther.getServerRawIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getServerRawTrackerImpressionId();
		result = 37 * result + (getServerRawIp() == null ? 0 : this.getServerRawIp().hashCode());
		return result;
	}

}
