package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataSummaryChannelDaily generated by hbm2java
 */
public class DataSummaryChannelDaily implements java.io.Serializable {

	private Long dataSummaryChannelDailyId;

	private Date day;

	private int channelId;

	private int zoneId;

	private int forecastImpressions;

	private int actualImpressions;

	public DataSummaryChannelDaily() {
	}

	public DataSummaryChannelDaily(Date day, int channelId, int zoneId, int forecastImpressions, int actualImpressions) {
		this.day = day;
		this.channelId = channelId;
		this.zoneId = zoneId;
		this.forecastImpressions = forecastImpressions;
		this.actualImpressions = actualImpressions;
	}

	public Long getDataSummaryChannelDailyId() {
		return this.dataSummaryChannelDailyId;
	}

	public void setDataSummaryChannelDailyId(Long dataSummaryChannelDailyId) {
		this.dataSummaryChannelDailyId = dataSummaryChannelDailyId;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public int getForecastImpressions() {
		return this.forecastImpressions;
	}

	public void setForecastImpressions(int forecastImpressions) {
		this.forecastImpressions = forecastImpressions;
	}

	public int getActualImpressions() {
		return this.actualImpressions;
	}

	public void setActualImpressions(int actualImpressions) {
		this.actualImpressions = actualImpressions;
	}

}
