package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataSummaryAdZoneAssoc generated by hbm2java
 */
public class DataSummaryAdZoneAssoc implements java.io.Serializable {

	private Long dataSummaryAdZoneAssocId;

	private int operationInterval;

	private int operationIntervalId;

	private Date intervalStart;

	private Date intervalEnd;

	private int adId;

	private int zoneId;

	private int requiredImpressions;

	private int requestedImpressions;

	private double priority;

	private Double priorityFactor;

	private short priorityFactorLimited;

	private Double pastZoneTrafficFraction;

	private Date created;

	private int createdBy;

	private Date expired;

	private Integer expiredBy;

	private boolean toBeDelivered;

	public DataSummaryAdZoneAssoc() {
	}

	public DataSummaryAdZoneAssoc(int operationInterval, int operationIntervalId, Date intervalStart, Date intervalEnd, int adId, int zoneId, int requiredImpressions, int requestedImpressions,
			double priority, short priorityFactorLimited, Date created, int createdBy, boolean toBeDelivered) {
		this.operationInterval = operationInterval;
		this.operationIntervalId = operationIntervalId;
		this.intervalStart = intervalStart;
		this.intervalEnd = intervalEnd;
		this.adId = adId;
		this.zoneId = zoneId;
		this.requiredImpressions = requiredImpressions;
		this.requestedImpressions = requestedImpressions;
		this.priority = priority;
		this.priorityFactorLimited = priorityFactorLimited;
		this.created = created;
		this.createdBy = createdBy;
		this.toBeDelivered = toBeDelivered;
	}

	public DataSummaryAdZoneAssoc(int operationInterval, int operationIntervalId, Date intervalStart, Date intervalEnd, int adId, int zoneId, int requiredImpressions, int requestedImpressions,
			double priority, Double priorityFactor, short priorityFactorLimited, Double pastZoneTrafficFraction, Date created, int createdBy, Date expired, Integer expiredBy, boolean toBeDelivered) {
		this.operationInterval = operationInterval;
		this.operationIntervalId = operationIntervalId;
		this.intervalStart = intervalStart;
		this.intervalEnd = intervalEnd;
		this.adId = adId;
		this.zoneId = zoneId;
		this.requiredImpressions = requiredImpressions;
		this.requestedImpressions = requestedImpressions;
		this.priority = priority;
		this.priorityFactor = priorityFactor;
		this.priorityFactorLimited = priorityFactorLimited;
		this.pastZoneTrafficFraction = pastZoneTrafficFraction;
		this.created = created;
		this.createdBy = createdBy;
		this.expired = expired;
		this.expiredBy = expiredBy;
		this.toBeDelivered = toBeDelivered;
	}

	public Long getDataSummaryAdZoneAssocId() {
		return this.dataSummaryAdZoneAssocId;
	}

	public void setDataSummaryAdZoneAssocId(Long dataSummaryAdZoneAssocId) {
		this.dataSummaryAdZoneAssocId = dataSummaryAdZoneAssocId;
	}

	public int getOperationInterval() {
		return this.operationInterval;
	}

	public void setOperationInterval(int operationInterval) {
		this.operationInterval = operationInterval;
	}

	public int getOperationIntervalId() {
		return this.operationIntervalId;
	}

	public void setOperationIntervalId(int operationIntervalId) {
		this.operationIntervalId = operationIntervalId;
	}

	public Date getIntervalStart() {
		return this.intervalStart;
	}

	public void setIntervalStart(Date intervalStart) {
		this.intervalStart = intervalStart;
	}

	public Date getIntervalEnd() {
		return this.intervalEnd;
	}

	public void setIntervalEnd(Date intervalEnd) {
		this.intervalEnd = intervalEnd;
	}

	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public int getRequiredImpressions() {
		return this.requiredImpressions;
	}

	public void setRequiredImpressions(int requiredImpressions) {
		this.requiredImpressions = requiredImpressions;
	}

	public int getRequestedImpressions() {
		return this.requestedImpressions;
	}

	public void setRequestedImpressions(int requestedImpressions) {
		this.requestedImpressions = requestedImpressions;
	}

	public double getPriority() {
		return this.priority;
	}

	public void setPriority(double priority) {
		this.priority = priority;
	}

	public Double getPriorityFactor() {
		return this.priorityFactor;
	}

	public void setPriorityFactor(Double priorityFactor) {
		this.priorityFactor = priorityFactor;
	}

	public short getPriorityFactorLimited() {
		return this.priorityFactorLimited;
	}

	public void setPriorityFactorLimited(short priorityFactorLimited) {
		this.priorityFactorLimited = priorityFactorLimited;
	}

	public Double getPastZoneTrafficFraction() {
		return this.pastZoneTrafficFraction;
	}

	public void setPastZoneTrafficFraction(Double pastZoneTrafficFraction) {
		this.pastZoneTrafficFraction = pastZoneTrafficFraction;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getExpired() {
		return this.expired;
	}

	public void setExpired(Date expired) {
		this.expired = expired;
	}

	public Integer getExpiredBy() {
		return this.expiredBy;
	}

	public void setExpiredBy(Integer expiredBy) {
		this.expiredBy = expiredBy;
	}

	public boolean isToBeDelivered() {
		return this.toBeDelivered;
	}

	public void setToBeDelivered(boolean toBeDelivered) {
		this.toBeDelivered = toBeDelivered;
	}

}
