package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataBktM generated by hbm2java
 */
public class DataBktM implements java.io.Serializable {

	private DataBktMId id;

	private int count;

	public DataBktM() {
	}

	public DataBktM(DataBktMId id, int count) {
		this.id = id;
		this.count = count;
	}

	public DataBktMId getId() {
		return this.id;
	}

	public void setId(DataBktMId id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
