package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataRawTrackerVariableValueId generated by hbm2java
 */
public class DataRawTrackerVariableValueId implements java.io.Serializable {

	private long serverRawTrackerImpressionId;

	private String serverRawIp;

	private int trackerVariableId;

	public DataRawTrackerVariableValueId() {
	}

	public DataRawTrackerVariableValueId(long serverRawTrackerImpressionId, String serverRawIp, int trackerVariableId) {
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
		this.serverRawIp = serverRawIp;
		this.trackerVariableId = trackerVariableId;
	}

	public long getServerRawTrackerImpressionId() {
		return this.serverRawTrackerImpressionId;
	}

	public void setServerRawTrackerImpressionId(long serverRawTrackerImpressionId) {
		this.serverRawTrackerImpressionId = serverRawTrackerImpressionId;
	}

	public String getServerRawIp() {
		return this.serverRawIp;
	}

	public void setServerRawIp(String serverRawIp) {
		this.serverRawIp = serverRawIp;
	}

	public int getTrackerVariableId() {
		return this.trackerVariableId;
	}

	public void setTrackerVariableId(int trackerVariableId) {
		this.trackerVariableId = trackerVariableId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataRawTrackerVariableValueId))
			return false;
		DataRawTrackerVariableValueId castOther = (DataRawTrackerVariableValueId) other;

		return (this.getServerRawTrackerImpressionId() == castOther.getServerRawTrackerImpressionId())
				&& ((this.getServerRawIp() == castOther.getServerRawIp()) || (this.getServerRawIp() != null && castOther.getServerRawIp() != null && this.getServerRawIp().equals(
						castOther.getServerRawIp()))) && (this.getTrackerVariableId() == castOther.getTrackerVariableId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getServerRawTrackerImpressionId();
		result = 37 * result + (getServerRawIp() == null ? 0 : this.getServerRawIp().hashCode());
		result = 37 * result + this.getTrackerVariableId();
		return result;
	}

}
