package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataRawAdRequest generated by hbm2java
 */
public class DataRawAdRequest implements java.io.Serializable {

	private DataRawAdRequestId id;

	public DataRawAdRequest() {
	}

	public DataRawAdRequest(DataRawAdRequestId id) {
		this.id = id;
	}

	public DataRawAdRequestId getId() {
		return this.id;
	}

	public void setId(DataRawAdRequestId id) {
		this.id = id;
	}

}
