package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataBktAId generated by hbm2java
 */
public class DataBktAId implements java.io.Serializable {

	private long serverConvId;

	private String serverIp;

	public DataBktAId() {
	}

	public DataBktAId(long serverConvId, String serverIp) {
		this.serverConvId = serverConvId;
		this.serverIp = serverIp;
	}

	public long getServerConvId() {
		return this.serverConvId;
	}

	public void setServerConvId(long serverConvId) {
		this.serverConvId = serverConvId;
	}

	public String getServerIp() {
		return this.serverIp;
	}

	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataBktAId))
			return false;
		DataBktAId castOther = (DataBktAId) other;

		return (this.getServerConvId() == castOther.getServerConvId())
				&& ((this.getServerIp() == castOther.getServerIp()) || (this.getServerIp() != null && castOther.getServerIp() != null && this.getServerIp().equals(castOther.getServerIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getServerConvId();
		result = 37 * result + (getServerIp() == null ? 0 : this.getServerIp().hashCode());
		return result;
	}

}
