package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataBktC generated by hbm2java
 */
public class DataBktC implements java.io.Serializable {

	private DataBktCId id;

	private int count;

	public DataBktC() {
	}

	public DataBktC(DataBktCId id, int count) {
		this.id = id;
		this.count = count;
	}

	public DataBktCId getId() {
		return this.id;
	}

	public void setId(DataBktCId id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
