package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataIntermediateAdVariableValue generated by hbm2java
 */
public class DataIntermediateAdVariableValue implements java.io.Serializable {

	private Long dataIntermediateAdVariableValueId;

	private long dataIntermediateAdConnectionId;

	private int trackerVariableId;

	private String value;

	public DataIntermediateAdVariableValue() {
	}

	public DataIntermediateAdVariableValue(long dataIntermediateAdConnectionId, int trackerVariableId) {
		this.dataIntermediateAdConnectionId = dataIntermediateAdConnectionId;
		this.trackerVariableId = trackerVariableId;
	}

	public DataIntermediateAdVariableValue(long dataIntermediateAdConnectionId, int trackerVariableId, String value) {
		this.dataIntermediateAdConnectionId = dataIntermediateAdConnectionId;
		this.trackerVariableId = trackerVariableId;
		this.value = value;
	}

	public Long getDataIntermediateAdVariableValueId() {
		return this.dataIntermediateAdVariableValueId;
	}

	public void setDataIntermediateAdVariableValueId(Long dataIntermediateAdVariableValueId) {
		this.dataIntermediateAdVariableValueId = dataIntermediateAdVariableValueId;
	}

	public long getDataIntermediateAdConnectionId() {
		return this.dataIntermediateAdConnectionId;
	}

	public void setDataIntermediateAdConnectionId(long dataIntermediateAdConnectionId) {
		this.dataIntermediateAdConnectionId = dataIntermediateAdConnectionId;
	}

	public int getTrackerVariableId() {
		return this.trackerVariableId;
	}

	public void setTrackerVariableId(int trackerVariableId) {
		this.trackerVariableId = trackerVariableId;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
