package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * DataBktR generated by hbm2java
 */
public class DataBktR implements java.io.Serializable {

	private DataBktRId id;

	private int count;

	public DataBktR() {
	}

	public DataBktR(DataBktRId id, int count) {
		this.id = id;
		this.count = count;
	}

	public DataBktRId getId() {
		return this.id;
	}

	public void setId(DataBktRId id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
