package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketSetting generated by hbm2java
 */
public class ExtMarketSetting implements java.io.Serializable {

	private ExtMarketSettingId id;

	public ExtMarketSetting() {
	}

	public ExtMarketSetting(ExtMarketSettingId id) {
		this.id = id;
	}

	public ExtMarketSettingId getId() {
		return this.id;
	}

	public void setId(ExtMarketSettingId id) {
		this.id = id;
	}

}
