package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketAdvertiser generated by hbm2java
 */
public class ExtMarketAdvertiser implements java.io.Serializable {

	private ExtMarketAdvertiserId id;

	public ExtMarketAdvertiser() {
	}

	public ExtMarketAdvertiser(ExtMarketAdvertiserId id) {
		this.id = id;
	}

	public ExtMarketAdvertiserId getId() {
		return this.id;
	}

	public void setId(ExtMarketAdvertiserId id) {
		this.id = id;
	}

}
