package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketStats generated by hbm2java
 */
public class ExtMarketStats implements java.io.Serializable {

	private ExtMarketStatsId id;

	public ExtMarketStats() {
	}

	public ExtMarketStats(ExtMarketStatsId id) {
		this.id = id;
	}

	public ExtMarketStatsId getId() {
		return this.id;
	}

	public void setId(ExtMarketStatsId id) {
		this.id = id;
	}

}
