package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketWebsitePref generated by hbm2java
 */
public class ExtMarketWebsitePref implements java.io.Serializable {

	private int affiliateid;

	private String websiteId;

	private String isUrlSynchronized;

	public ExtMarketWebsitePref() {
	}

	public ExtMarketWebsitePref(int affiliateid, String websiteId) {
		this.affiliateid = affiliateid;
		this.websiteId = websiteId;
	}

	public ExtMarketWebsitePref(int affiliateid, String websiteId, String isUrlSynchronized) {
		this.affiliateid = affiliateid;
		this.websiteId = websiteId;
		this.isUrlSynchronized = isUrlSynchronized;
	}

	public int getAffiliateid() {
		return this.affiliateid;
	}

	public void setAffiliateid(int affiliateid) {
		this.affiliateid = affiliateid;
	}

	public String getWebsiteId() {
		return this.websiteId;
	}

	public void setWebsiteId(String websiteId) {
		this.websiteId = websiteId;
	}

	public String getIsUrlSynchronized() {
		return this.isUrlSynchronized;
	}

	public void setIsUrlSynchronized(String isUrlSynchronized) {
		this.isUrlSynchronized = isUrlSynchronized;
	}

}
