package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ExtMarketWebStatsId generated by hbm2java
 */
public class ExtMarketWebStatsId implements java.io.Serializable {

	private String PWebsiteId;

	private int impressions;

	private Date dateTime;

	private BigDecimal revenue;

	private Short width;

	private Short height;

	public ExtMarketWebStatsId() {
	}

	public ExtMarketWebStatsId(String PWebsiteId, int impressions) {
		this.PWebsiteId = PWebsiteId;
		this.impressions = impressions;
	}

	public ExtMarketWebStatsId(String PWebsiteId, int impressions, Date dateTime, BigDecimal revenue, Short width, Short height) {
		this.PWebsiteId = PWebsiteId;
		this.impressions = impressions;
		this.dateTime = dateTime;
		this.revenue = revenue;
		this.width = width;
		this.height = height;
	}

	public String getPWebsiteId() {
		return this.PWebsiteId;
	}

	public void setPWebsiteId(String PWebsiteId) {
		this.PWebsiteId = PWebsiteId;
	}

	public int getImpressions() {
		return this.impressions;
	}

	public void setImpressions(int impressions) {
		this.impressions = impressions;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

	public Short getWidth() {
		return this.width;
	}

	public void setWidth(Short width) {
		this.width = width;
	}

	public Short getHeight() {
		return this.height;
	}

	public void setHeight(Short height) {
		this.height = height;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExtMarketWebStatsId))
			return false;
		ExtMarketWebStatsId castOther = (ExtMarketWebStatsId) other;

		return ((this.getPWebsiteId() == castOther.getPWebsiteId()) || (this.getPWebsiteId() != null && castOther.getPWebsiteId() != null && this.getPWebsiteId().equals(castOther.getPWebsiteId())))
				&& (this.getImpressions() == castOther.getImpressions())
				&& ((this.getDateTime() == castOther.getDateTime()) || (this.getDateTime() != null && castOther.getDateTime() != null && this.getDateTime().equals(castOther.getDateTime())))
				&& ((this.getRevenue() == castOther.getRevenue()) || (this.getRevenue() != null && castOther.getRevenue() != null && this.getRevenue().equals(castOther.getRevenue())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null && castOther.getWidth() != null && this.getWidth().equals(castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null && castOther.getHeight() != null && this.getHeight().equals(castOther.getHeight())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPWebsiteId() == null ? 0 : this.getPWebsiteId().hashCode());
		result = 37 * result + this.getImpressions();
		result = 37 * result + (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		result = 37 * result + (getRevenue() == null ? 0 : this.getRevenue().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		return result;
	}

}
