package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketSettingId generated by hbm2java
 */
public class ExtMarketSettingId implements java.io.Serializable {

	private int marketSettingId;

	private int marketSettingTypeId;

	private int ownerTypeId;

	private int ownerId;

	public ExtMarketSettingId() {
	}

	public ExtMarketSettingId(int marketSettingId, int marketSettingTypeId, int ownerTypeId, int ownerId) {
		this.marketSettingId = marketSettingId;
		this.marketSettingTypeId = marketSettingTypeId;
		this.ownerTypeId = ownerTypeId;
		this.ownerId = ownerId;
	}

	public int getMarketSettingId() {
		return this.marketSettingId;
	}

	public void setMarketSettingId(int marketSettingId) {
		this.marketSettingId = marketSettingId;
	}

	public int getMarketSettingTypeId() {
		return this.marketSettingTypeId;
	}

	public void setMarketSettingTypeId(int marketSettingTypeId) {
		this.marketSettingTypeId = marketSettingTypeId;
	}

	public int getOwnerTypeId() {
		return this.ownerTypeId;
	}

	public void setOwnerTypeId(int ownerTypeId) {
		this.ownerTypeId = ownerTypeId;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExtMarketSettingId))
			return false;
		ExtMarketSettingId castOther = (ExtMarketSettingId) other;

		return (this.getMarketSettingId() == castOther.getMarketSettingId()) && (this.getMarketSettingTypeId() == castOther.getMarketSettingTypeId())
				&& (this.getOwnerTypeId() == castOther.getOwnerTypeId()) && (this.getOwnerId() == castOther.getOwnerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMarketSettingId();
		result = 37 * result + this.getMarketSettingTypeId();
		result = 37 * result + this.getOwnerTypeId();
		result = 37 * result + this.getOwnerId();
		return result;
	}

}
