package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ExtMarketCampaignPref generated by hbm2java
 */
public class ExtMarketCampaignPref implements java.io.Serializable {

	private int campaignid;

	private Short isEnabled;

	private BigDecimal floorPrice;

	public ExtMarketCampaignPref() {
	}

	public ExtMarketCampaignPref(int campaignid) {
		this.campaignid = campaignid;
	}

	public ExtMarketCampaignPref(int campaignid, Short isEnabled, BigDecimal floorPrice) {
		this.campaignid = campaignid;
		this.isEnabled = isEnabled;
		this.floorPrice = floorPrice;
	}

	public int getCampaignid() {
		return this.campaignid;
	}

	public void setCampaignid(int campaignid) {
		this.campaignid = campaignid;
	}

	public Short getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Short isEnabled) {
		this.isEnabled = isEnabled;
	}

	public BigDecimal getFloorPrice() {
		return this.floorPrice;
	}

	public void setFloorPrice(BigDecimal floorPrice) {
		this.floorPrice = floorPrice;
	}

}
