package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketGeneralPrefId generated by hbm2java
 */
public class ExtMarketGeneralPrefId implements java.io.Serializable {

	private int accountId;

	private String name;

	public ExtMarketGeneralPrefId() {
	}

	public ExtMarketGeneralPrefId(int accountId, String name) {
		this.accountId = accountId;
		this.name = name;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExtMarketGeneralPrefId))
			return false;
		ExtMarketGeneralPrefId castOther = (ExtMarketGeneralPrefId) other;

		return (this.getAccountId() == castOther.getAccountId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
