package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketGeneralPref generated by hbm2java
 */
public class ExtMarketGeneralPref implements java.io.Serializable {

	private ExtMarketGeneralPrefId id;

	private String value;

	public ExtMarketGeneralPref() {
	}

	public ExtMarketGeneralPref(ExtMarketGeneralPrefId id, String value) {
		this.id = id;
		this.value = value;
	}

	public ExtMarketGeneralPrefId getId() {
		return this.id;
	}

	public void setId(ExtMarketGeneralPrefId id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
