package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * ExtMarketWebStats generated by hbm2java
 */
public class ExtMarketWebStats implements java.io.Serializable {

	private ExtMarketWebStatsId id;

	public ExtMarketWebStats() {
	}

	public ExtMarketWebStats(ExtMarketWebStatsId id) {
		this.id = id;
	}

	public ExtMarketWebStatsId getId() {
		return this.id;
	}

	public void setId(ExtMarketWebStatsId id) {
		this.id = id;
	}

}
