package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private String filename;

	private byte[] contents;

	private Date TStamp;

	public Images() {
	}

	public Images(String filename, byte[] contents) {
		this.filename = filename;
		this.contents = contents;
	}

	public Images(String filename, byte[] contents, Date TStamp) {
		this.filename = filename;
		this.contents = contents;
		this.TStamp = TStamp;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public byte[] getContents() {
		return this.contents;
	}

	public void setContents(byte[] contents) {
		this.contents = contents;
	}

	public Date getTStamp() {
		return this.TStamp;
	}

	public void setTStamp(Date TStamp) {
		this.TStamp = TStamp;
	}

}
