package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogMaintenancePriority generated by hbm2java
 */
public class LogMaintenancePriority implements java.io.Serializable {

	private Integer logMaintenancePriorityId;

	private Date startRun;

	private Date endRun;

	private int operationInterval;

	private int duration;

	private byte runType;

	private Date updatedTo;

	public LogMaintenancePriority() {
	}

	public LogMaintenancePriority(Date startRun, Date endRun, int operationInterval, int duration, byte runType) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.operationInterval = operationInterval;
		this.duration = duration;
		this.runType = runType;
	}

	public LogMaintenancePriority(Date startRun, Date endRun, int operationInterval, int duration, byte runType, Date updatedTo) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.operationInterval = operationInterval;
		this.duration = duration;
		this.runType = runType;
		this.updatedTo = updatedTo;
	}

	public Integer getLogMaintenancePriorityId() {
		return this.logMaintenancePriorityId;
	}

	public void setLogMaintenancePriorityId(Integer logMaintenancePriorityId) {
		this.logMaintenancePriorityId = logMaintenancePriorityId;
	}

	public Date getStartRun() {
		return this.startRun;
	}

	public void setStartRun(Date startRun) {
		this.startRun = startRun;
	}

	public Date getEndRun() {
		return this.endRun;
	}

	public void setEndRun(Date endRun) {
		this.endRun = endRun;
	}

	public int getOperationInterval() {
		return this.operationInterval;
	}

	public void setOperationInterval(int operationInterval) {
		this.operationInterval = operationInterval;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public byte getRunType() {
		return this.runType;
	}

	public void setRunType(byte runType) {
		this.runType = runType;
	}

	public Date getUpdatedTo() {
		return this.updatedTo;
	}

	public void setUpdatedTo(Date updatedTo) {
		this.updatedTo = updatedTo;
	}

}
