package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogMaintenanceStatistics generated by hbm2java
 */
public class LogMaintenanceStatistics implements java.io.Serializable {

	private Integer logMaintenanceStatisticsId;

	private Date startRun;

	private Date endRun;

	private int duration;

	private Integer adserverRunType;

	private Integer searchRunType;

	private Integer trackerRunType;

	private Date updatedTo;

	public LogMaintenanceStatistics() {
	}

	public LogMaintenanceStatistics(Date startRun, Date endRun, int duration) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.duration = duration;
	}

	public LogMaintenanceStatistics(Date startRun, Date endRun, int duration, Integer adserverRunType, Integer searchRunType, Integer trackerRunType, Date updatedTo) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.duration = duration;
		this.adserverRunType = adserverRunType;
		this.searchRunType = searchRunType;
		this.trackerRunType = trackerRunType;
		this.updatedTo = updatedTo;
	}

	public Integer getLogMaintenanceStatisticsId() {
		return this.logMaintenanceStatisticsId;
	}

	public void setLogMaintenanceStatisticsId(Integer logMaintenanceStatisticsId) {
		this.logMaintenanceStatisticsId = logMaintenanceStatisticsId;
	}

	public Date getStartRun() {
		return this.startRun;
	}

	public void setStartRun(Date startRun) {
		this.startRun = startRun;
	}

	public Date getEndRun() {
		return this.endRun;
	}

	public void setEndRun(Date endRun) {
		this.endRun = endRun;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public Integer getAdserverRunType() {
		return this.adserverRunType;
	}

	public void setAdserverRunType(Integer adserverRunType) {
		this.adserverRunType = adserverRunType;
	}

	public Integer getSearchRunType() {
		return this.searchRunType;
	}

	public void setSearchRunType(Integer searchRunType) {
		this.searchRunType = searchRunType;
	}

	public Integer getTrackerRunType() {
		return this.trackerRunType;
	}

	public void setTrackerRunType(Integer trackerRunType) {
		this.trackerRunType = trackerRunType;
	}

	public Date getUpdatedTo() {
		return this.updatedTo;
	}

	public void setUpdatedTo(Date updatedTo) {
		this.updatedTo = updatedTo;
	}

}
