package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogMaintenanceForecasting generated by hbm2java
 */
public class LogMaintenanceForecasting implements java.io.Serializable {

	private Integer logMaintenanceForecastingId;

	private Date startRun;

	private Date endRun;

	private int operationInterval;

	private int duration;

	private Date updatedTo;

	public LogMaintenanceForecasting() {
	}

	public LogMaintenanceForecasting(Date startRun, Date endRun, int operationInterval, int duration) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.operationInterval = operationInterval;
		this.duration = duration;
	}

	public LogMaintenanceForecasting(Date startRun, Date endRun, int operationInterval, int duration, Date updatedTo) {
		this.startRun = startRun;
		this.endRun = endRun;
		this.operationInterval = operationInterval;
		this.duration = duration;
		this.updatedTo = updatedTo;
	}

	public Integer getLogMaintenanceForecastingId() {
		return this.logMaintenanceForecastingId;
	}

	public void setLogMaintenanceForecastingId(Integer logMaintenanceForecastingId) {
		this.logMaintenanceForecastingId = logMaintenanceForecastingId;
	}

	public Date getStartRun() {
		return this.startRun;
	}

	public void setStartRun(Date startRun) {
		this.startRun = startRun;
	}

	public Date getEndRun() {
		return this.endRun;
	}

	public void setEndRun(Date endRun) {
		this.endRun = endRun;
	}

	public int getOperationInterval() {
		return this.operationInterval;
	}

	public void setOperationInterval(int operationInterval) {
		this.operationInterval = operationInterval;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public Date getUpdatedTo() {
		return this.updatedTo;
	}

	public void setUpdatedTo(Date updatedTo) {
		this.updatedTo = updatedTo;
	}

}
