package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PasswordRecovery generated by hbm2java
 */
public class PasswordRecovery implements java.io.Serializable {

	private PasswordRecoveryId id;

	private String recoveryId;

	private Date updated;

	public PasswordRecovery() {
	}

	public PasswordRecovery(PasswordRecoveryId id, String recoveryId, Date updated) {
		this.id = id;
		this.recoveryId = recoveryId;
		this.updated = updated;
	}

	public PasswordRecoveryId getId() {
		return this.id;
	}

	public void setId(PasswordRecoveryId id) {
		this.id = id;
	}

	public String getRecoveryId() {
		return this.recoveryId;
	}

	public void setRecoveryId(String recoveryId) {
		this.recoveryId = recoveryId;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
