package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * PasswordRecoveryId generated by hbm2java
 */
public class PasswordRecoveryId implements java.io.Serializable {

	private String userType;

	private int userId;

	public PasswordRecoveryId() {
	}

	public PasswordRecoveryId(String userType, int userId) {
		this.userType = userType;
		this.userId = userId;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasswordRecoveryId))
			return false;
		PasswordRecoveryId castOther = (PasswordRecoveryId) other;

		return ((this.getUserType() == castOther.getUserType()) || (this.getUserType() != null && castOther.getUserType() != null && this.getUserType().equals(castOther.getUserType())))
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserType() == null ? 0 : this.getUserType().hashCode());
		result = 37 * result + this.getUserId();
		return result;
	}

}
