package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * StatsVast generated by hbm2java
 */
public class StatsVast implements java.io.Serializable {

	private StatsVastId id;

	public StatsVast() {
	}

	public StatsVast(StatsVastId id) {
		this.id = id;
	}

	public StatsVastId getId() {
		return this.id;
	}

	public void setId(StatsVastId id) {
		this.id = id;
	}

}
