package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TargetstatsId generated by hbm2java
 */
public class TargetstatsId implements java.io.Serializable {

	private Date day;

	private int campaignid;

	private int target;

	private int views;

	private byte modified;

	public TargetstatsId() {
	}

	public TargetstatsId(Date day, int campaignid, int target, int views, byte modified) {
		this.day = day;
		this.campaignid = campaignid;
		this.target = target;
		this.views = views;
		this.modified = modified;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public int getCampaignid() {
		return this.campaignid;
	}

	public void setCampaignid(int campaignid) {
		this.campaignid = campaignid;
	}

	public int getTarget() {
		return this.target;
	}

	public void setTarget(int target) {
		this.target = target;
	}

	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public byte getModified() {
		return this.modified;
	}

	public void setModified(byte modified) {
		this.modified = modified;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TargetstatsId))
			return false;
		TargetstatsId castOther = (TargetstatsId) other;

		return ((this.getDay() == castOther.getDay()) || (this.getDay() != null && castOther.getDay() != null && this.getDay().equals(castOther.getDay())))
				&& (this.getCampaignid() == castOther.getCampaignid()) && (this.getTarget() == castOther.getTarget()) && (this.getViews() == castOther.getViews())
				&& (this.getModified() == castOther.getModified());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDay() == null ? 0 : this.getDay().hashCode());
		result = 37 * result + this.getCampaignid();
		result = 37 * result + this.getTarget();
		result = 37 * result + this.getViews();
		result = 37 * result + this.getModified();
		return result;
	}

}
