package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * Targetstats generated by hbm2java
 */
public class Targetstats implements java.io.Serializable {

	private TargetstatsId id;

	public Targetstats() {
	}

	public Targetstats(TargetstatsId id) {
		this.id = id;
	}

	public TargetstatsId getId() {
		return this.id;
	}

	public void setId(TargetstatsId id) {
		this.id = id;
	}

}
