package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Trackers generated by hbm2java
 */
public class Trackers implements java.io.Serializable {

	private Integer trackerid;

	private String trackername;

	private String description;

	private int clientid;

	private int viewwindow;

	private int clickwindow;

	private int blockwindow;

	private short status;

	private short type;

	private String linkcampaigns;

	private String variablemethod;

	private String appendcode;

	private Date updated;

	public Trackers() {
	}

	public Trackers(String trackername, String description, int clientid, int viewwindow, int clickwindow, int blockwindow, short status, short type, String linkcampaigns, String variablemethod,
			String appendcode, Date updated) {
		this.trackername = trackername;
		this.description = description;
		this.clientid = clientid;
		this.viewwindow = viewwindow;
		this.clickwindow = clickwindow;
		this.blockwindow = blockwindow;
		this.status = status;
		this.type = type;
		this.linkcampaigns = linkcampaigns;
		this.variablemethod = variablemethod;
		this.appendcode = appendcode;
		this.updated = updated;
	}

	public Integer getTrackerid() {
		return this.trackerid;
	}

	public void setTrackerid(Integer trackerid) {
		this.trackerid = trackerid;
	}

	public String getTrackername() {
		return this.trackername;
	}

	public void setTrackername(String trackername) {
		this.trackername = trackername;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getClientid() {
		return this.clientid;
	}

	public void setClientid(int clientid) {
		this.clientid = clientid;
	}

	public int getViewwindow() {
		return this.viewwindow;
	}

	public void setViewwindow(int viewwindow) {
		this.viewwindow = viewwindow;
	}

	public int getClickwindow() {
		return this.clickwindow;
	}

	public void setClickwindow(int clickwindow) {
		this.clickwindow = clickwindow;
	}

	public int getBlockwindow() {
		return this.blockwindow;
	}

	public void setBlockwindow(int blockwindow) {
		this.blockwindow = blockwindow;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public String getLinkcampaigns() {
		return this.linkcampaigns;
	}

	public void setLinkcampaigns(String linkcampaigns) {
		this.linkcampaigns = linkcampaigns;
	}

	public String getVariablemethod() {
		return this.variablemethod;
	}

	public void setVariablemethod(String variablemethod) {
		this.variablemethod = variablemethod;
	}

	public String getAppendcode() {
		return this.appendcode;
	}

	public void setAppendcode(String appendcode) {
		this.appendcode = appendcode;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
