package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * TrackerAppend generated by hbm2java
 */
public class TrackerAppend implements java.io.Serializable {

	private Integer trackerAppendId;

	private int trackerId;

	private int rank;

	private String tagcode;

	private String paused;

	private String autotrack;

	public TrackerAppend() {
	}

	public TrackerAppend(int trackerId, int rank, String tagcode, String paused, String autotrack) {
		this.trackerId = trackerId;
		this.rank = rank;
		this.tagcode = tagcode;
		this.paused = paused;
		this.autotrack = autotrack;
	}

	public Integer getTrackerAppendId() {
		return this.trackerAppendId;
	}

	public void setTrackerAppendId(Integer trackerAppendId) {
		this.trackerAppendId = trackerAppendId;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getTagcode() {
		return this.tagcode;
	}

	public void setTagcode(String tagcode) {
		this.tagcode = tagcode;
	}

	public String getPaused() {
		return this.paused;
	}

	public void setPaused(String paused) {
		this.paused = paused;
	}

	public String getAutotrack() {
		return this.autotrack;
	}

	public void setAutotrack(String autotrack) {
		this.autotrack = autotrack;
	}

}
