package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UpgradeAction generated by hbm2java
 */
public class UpgradeAction implements java.io.Serializable {

	private Integer upgradeActionId;

	private String upgradeName;

	private String versionTo;

	private String versionFrom;

	private int action;

	private String description;

	private String logfile;

	private String confbackup;

	private Date updated;

	public UpgradeAction() {
	}

	public UpgradeAction(String versionTo, int action) {
		this.versionTo = versionTo;
		this.action = action;
	}

	public UpgradeAction(String upgradeName, String versionTo, String versionFrom, int action, String description, String logfile, String confbackup, Date updated) {
		this.upgradeName = upgradeName;
		this.versionTo = versionTo;
		this.versionFrom = versionFrom;
		this.action = action;
		this.description = description;
		this.logfile = logfile;
		this.confbackup = confbackup;
		this.updated = updated;
	}

	public Integer getUpgradeActionId() {
		return this.upgradeActionId;
	}

	public void setUpgradeActionId(Integer upgradeActionId) {
		this.upgradeActionId = upgradeActionId;
	}

	public String getUpgradeName() {
		return this.upgradeName;
	}

	public void setUpgradeName(String upgradeName) {
		this.upgradeName = upgradeName;
	}

	public String getVersionTo() {
		return this.versionTo;
	}

	public void setVersionTo(String versionTo) {
		this.versionTo = versionTo;
	}

	public String getVersionFrom() {
		return this.versionFrom;
	}

	public void setVersionFrom(String versionFrom) {
		this.versionFrom = versionFrom;
	}

	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLogfile() {
		return this.logfile;
	}

	public void setLogfile(String logfile) {
		this.logfile = logfile;
	}

	public String getConfbackup() {
		return this.confbackup;
	}

	public void setConfbackup(String confbackup) {
		this.confbackup = confbackup;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
