package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * Userlog generated by hbm2java
 */
public class Userlog implements java.io.Serializable {

	private Integer userlogid;

	private int timestamp;

	private byte usertype;

	private int userid;

	private int action;

	private Integer object;

	private String details;

	public Userlog() {
	}

	public Userlog(byte usertype, int userid, int action) {
		this.usertype = usertype;
		this.userid = userid;
		this.action = action;
	}

	public Userlog(byte usertype, int userid, int action, Integer object, String details) {
		this.usertype = usertype;
		this.userid = userid;
		this.action = action;
		this.object = object;
		this.details = details;
	}

	public Integer getUserlogid() {
		return this.userlogid;
	}

	public void setUserlogid(Integer userlogid) {
		this.userlogid = userlogid;
	}

	public int getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	public byte getUsertype() {
		return this.usertype;
	}

	public void setUsertype(byte usertype) {
		this.usertype = usertype;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

	public Integer getObject() {
		return this.object;
	}

	public void setObject(Integer object) {
		this.object = object;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

}
