package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;

	private String contactName;

	private String emailAddress;

	private String username;

	private String password;

	private String language;

	private Integer defaultAccountId;

	private String comments;

	private boolean active;

	private Integer ssoUserId;

	private Date dateCreated;

	private Date dateLastLogin;

	private Date emailUpdated;

	public Users() {
	}

	public Users(String contactName, String emailAddress, boolean active) {
		this.contactName = contactName;
		this.emailAddress = emailAddress;
		this.active = active;
	}

	public Users(String contactName, String emailAddress, String username, String password, String language, Integer defaultAccountId, String comments, boolean active, Integer ssoUserId,
			Date dateCreated, Date dateLastLogin, Date emailUpdated) {
		this.contactName = contactName;
		this.emailAddress = emailAddress;
		this.username = username;
		this.password = password;
		this.language = language;
		this.defaultAccountId = defaultAccountId;
		this.comments = comments;
		this.active = active;
		this.ssoUserId = ssoUserId;
		this.dateCreated = dateCreated;
		this.dateLastLogin = dateLastLogin;
		this.emailUpdated = emailUpdated;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Integer getDefaultAccountId() {
		return this.defaultAccountId;
	}

	public void setDefaultAccountId(Integer defaultAccountId) {
		this.defaultAccountId = defaultAccountId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Integer getSsoUserId() {
		return this.ssoUserId;
	}

	public void setSsoUserId(Integer ssoUserId) {
		this.ssoUserId = ssoUserId;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateLastLogin() {
		return this.dateLastLogin;
	}

	public void setDateLastLogin(Date dateLastLogin) {
		this.dateLastLogin = dateLastLogin;
	}

	public Date getEmailUpdated() {
		return this.emailUpdated;
	}

	public void setEmailUpdated(Date emailUpdated) {
		this.emailUpdated = emailUpdated;
	}

}
