package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * VariablePublisher generated by hbm2java
 */
public class VariablePublisher implements java.io.Serializable {

	private VariablePublisherId id;

	private boolean visible;

	public VariablePublisher() {
	}

	public VariablePublisher(VariablePublisherId id, boolean visible) {
		this.id = id;
		this.visible = visible;
	}

	public VariablePublisherId getId() {
		return this.id;
	}

	public void setId(VariablePublisherId id) {
		this.id = id;
	}

	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

}
