package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

/**
 * VariablePublisherId generated by hbm2java
 */
public class VariablePublisherId implements java.io.Serializable {

	private int variableId;

	private int publisherId;

	public VariablePublisherId() {
	}

	public VariablePublisherId(int variableId, int publisherId) {
		this.variableId = variableId;
		this.publisherId = publisherId;
	}

	public int getVariableId() {
		return this.variableId;
	}

	public void setVariableId(int variableId) {
		this.variableId = variableId;
	}

	public int getPublisherId() {
		return this.publisherId;
	}

	public void setPublisherId(int publisherId) {
		this.publisherId = publisherId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VariablePublisherId))
			return false;
		VariablePublisherId castOther = (VariablePublisherId) other;

		return (this.getVariableId() == castOther.getVariableId()) && (this.getPublisherId() == castOther.getPublisherId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVariableId();
		result = 37 * result + this.getPublisherId();
		return result;
	}

}
