package com.orbit.openx.model;

// Generated 25 f�vr. 2014 12:11:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Variables generated by hbm2java
 */
public class Variables implements java.io.Serializable {

	private Integer variableid;

	private int trackerid;

	private String name;

	private String description;

	private String datatype;

	private String purpose;

	private short rejectIfEmpty;

	private int isUnique;

	private int uniqueWindow;

	private String variablecode;

	private String hidden;

	private Date updated;

	public Variables() {
	}

	public Variables(int trackerid, String name, String datatype, short rejectIfEmpty, int isUnique, int uniqueWindow, String variablecode, String hidden, Date updated) {
		this.trackerid = trackerid;
		this.name = name;
		this.datatype = datatype;
		this.rejectIfEmpty = rejectIfEmpty;
		this.isUnique = isUnique;
		this.uniqueWindow = uniqueWindow;
		this.variablecode = variablecode;
		this.hidden = hidden;
		this.updated = updated;
	}

	public Variables(int trackerid, String name, String description, String datatype, String purpose, short rejectIfEmpty, int isUnique, int uniqueWindow, String variablecode, String hidden,
			Date updated) {
		this.trackerid = trackerid;
		this.name = name;
		this.description = description;
		this.datatype = datatype;
		this.purpose = purpose;
		this.rejectIfEmpty = rejectIfEmpty;
		this.isUnique = isUnique;
		this.uniqueWindow = uniqueWindow;
		this.variablecode = variablecode;
		this.hidden = hidden;
		this.updated = updated;
	}

	public Integer getVariableid() {
		return this.variableid;
	}

	public void setVariableid(Integer variableid) {
		this.variableid = variableid;
	}

	public int getTrackerid() {
		return this.trackerid;
	}

	public void setTrackerid(int trackerid) {
		this.trackerid = trackerid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public short getRejectIfEmpty() {
		return this.rejectIfEmpty;
	}

	public void setRejectIfEmpty(short rejectIfEmpty) {
		this.rejectIfEmpty = rejectIfEmpty;
	}

	public int getIsUnique() {
		return this.isUnique;
	}

	public void setIsUnique(int isUnique) {
		this.isUnique = isUnique;
	}

	public int getUniqueWindow() {
		return this.uniqueWindow;
	}

	public void setUniqueWindow(int uniqueWindow) {
		this.uniqueWindow = uniqueWindow;
	}

	public String getVariablecode() {
		return this.variablecode;
	}

	public void setVariablecode(String variablecode) {
		this.variablecode = variablecode;
	}

	public String getHidden() {
		return this.hidden;
	}

	public void setHidden(String hidden) {
		this.hidden = hidden;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
